backend/alloc/alloc.go, backend/common.go, backend/hostgw/hostgw.go, backend/udp/udp.go, backend/vxlan/vxlan.go, ipmasq.go, main.go
This is an attempt to have the same IP masquerading rules
across all backends. They work purely on address ranges and
without interface names.
Practically, VXLAN now has IP masquerade support.
Fixes #101
=> Factor out installing IP masquerading out of backends

backend/vxlan/vxlan.go
Otherwise, the process can exit prematurely if flanneld is started
before the host networking configuration is not yet completed.
=> Retry VXLAN interface creation if it fails

dist/build-aci.sh
This patch depends on:
- actool patch-manifest:
https://github.com/appc/spec/pull/258
- docker2aci on local files:
https://github.com/appc/docker2aci/issues/32
=> dist/build-aci.sh: build an aci

Godeps/Godeps.json, Godeps/_workspace/src/github.com/mitchellh/goamz/aws/attempt.go, Godeps/_workspace/src/github.com/mitchellh/goamz/aws/attempt_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/aws/aws.go, Godeps/_workspace/src/github.com/mitchellh/goamz/aws/aws_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/aws/client.go, Godeps/_workspace/src/github.com/mitchellh/goamz/aws/client_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/ec2.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/ec2_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/ec2i_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/ec2t_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/ec2test/filter.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/ec2test/server.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/export_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/responses_test.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/sign.go, Godeps/_workspace/src/github.com/mitchellh/goamz/ec2/sign_test.go, Godeps/_workspace/src/github.com/vaughan0/go-ini/LICENSE, Godeps/_workspace/src/github.com/vaughan0/go-ini/README.md, Godeps/_workspace/src/github.com/vaughan0/go-ini/ini.go, Godeps/_workspace/src/github.com/vaughan0/go-ini/ini_linux_test.go, Godeps/_workspace/src/github.com/vaughan0/go-ini/ini_test.go, Godeps/_workspace/src/github.com/vaughan0/go-ini/test.ini, README.md, backend/awsvpc/awsvpc.go, backend/awsvpc/ec2.go, main.go
The Amazon VPC backend adds routes to a VPC route table. Routing is then
handled by Amazon's infrastructure.
=> backend: Add Amazon VPC backend

backend/hostgw/hostgw.go, subnet/subnet.go
hostgw: fix the bug of lost route infomation when restart network
when we're using flannel with hostgw backend, if we unplug the network cable and then plug the network cable immediately, we find the route infomation will be lost and can never be recovered.  and of course we can not be routed to containers in other minor with k8s.  Our fix periodly check the routes information, and will fix it when route information lost.
=> fix the bug of lost route information when restart network

README.md, backend/awsvpc/awsvpc.go
using getAuth instead of getEnv allows goamz to acquire authentication
material from instance metadata as well as the environment.
=> backend/awsvpc: allow RBAC for instances

remote/remote_test.go, subnet/etcd.go, subnet/mock_registry.go, subnet/subnet_test.go
This fixes two bugs:
1. watch was not getting a snapshot with nil cursor.
2. watch was not advancing properly due to wrong index used.
=> properly handle nil cursor and use Etcd vs Modified index

backend/vxlan/device.go, backend/vxlan/routes.go, backend/vxlan/vxlan.go
Since L2 misses are still handled statically DOVE extensions are
no longer required.routes.go maintains the mappings. devices.go now monitors for L3 misses and vxlan is
updated to handleL3Misses.
Fixes #203
=> Dynamically handles L3 misses with vxlan backend

README.md
Adds:
1. Permissions required by EC2 running flannel.
2. Disabling of the source/destination checks.
3. Mentions the auto route table id detection feature.
=> Update README to detail aws requirements

dist/README.md, dist/build-docker.sh, dist/build-release.sh, dist/bump-release.sh
- Add README.md to document how to do a release
- Switch to using GO 1.4.2
- Add scripts to bump/tag a release
=> Update release tools

subnet/etcd.go, subnet/mock_registry.go, subnet/registry.go, subnet/subnet_test.go
When starting, only reuse the lease if it is still compatible
with the current network configuration. If values such as
Network, SubnetMin, SubnetMax, or SubnetLen have changed, the
lease may not be usuable in this case and should be deleted and
re-aquired.
Fixes #196
=> Assert lease is compat with config before reuse

main.go
Related to #216  ... If you mistakenly forget to add the right arg names to  flannel , then it just silently ignores them.  that causes alot of confusion .  Lets fail if there are wrong/bad/unknown/ignored args sent in, and fail fast.
=> Don't allow extra args

Documentation/client-server.md, Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/keepalive_listener.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/keepalive_listener_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/listener.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/listener_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_conn.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_dialer.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_dialer_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_listener.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_listener_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_transport.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/transport/timeout_transport_test.go, README.md, main.go, remote/client.go, remote/remote_test.go, remote/server.go
Analogous to etcd, optionally use TLS to encrypt communication
between the client and the server. Also, as an option, client side
certificates can be used to authenticate connecting clients.
Fixes #178 and #229
=> Add TLS support for client/server communication

backend/hostgw/hostgw.go
Route to local ext IP may get added when local docker0 is not yet setup, see:
[root@localhost ~]# ip route
default via 10.0.2.2 dev enp0s3
10.0.2.0/24 dev enp0s3  proto kernel  scope link  src 10.0.2.15
**10.10.176.0/20 via 172.17.8.101 dev enp0s8**
**10.10.176.0/20 dev docker0  proto kernel  scope link  src 10.10.176.1**
10.10.192.0/20 via 172.17.8.102 dev enp0s8
10.15.240.0/20 via 172.17.8.100 dev enp0s8
169.254.0.0/16 dev enp0s3  scope link  metric 1002
169.254.0.0/16 dev enp0s8  scope link  metric 1003
172.17.8.0/24 dev enp0s8  proto kernel  scope link  src 172.17.8.101
=> Ignore route to local ext IP in hostgw mode

backend/vxlan/vxlan.go
Bug fix where nil IP (byte slice) was dereferenced
and caused the goroutine to hang.
Fixes #260 and #267
=> vxlan: check of nil IP in fdb entry

remote/client.go, remote/remote_test.go, remote/transport.go
Due to https://github.com/golang/go/issues/11013 race conditions
in the remote testcases mean that HTTP requests aren't actually
canceled.  In client.go::httpDo() the goroutine that actually
runs the http.Do() may not execute until after that routine's
select{} loop, at which point the Context may have already been
canceled.  Unfortunately with Go < 1.5 there is a race in the
http.Transport package that drops cancellations on the floor.
This issue can be reproduced by using the remote_test.go hunks
that use a WaitGroup to wait for subnet.WatchLeases() to exit
after the Context is canceled, but not the client.go hunks.
Specifically, doTestWatch() calls cancel() before
watch.go::WatchLeases() calls sm.WatchLeases(), which in this
case is RemoteManager.WatchLeases(), which then calls …
=> remote: ensure testing HTTP requests are canceled

backend/hostgw/hostgw.go, backend/udp/udp.go, backend/vxlan/vxlan.go, remote/remote_test.go, subnet/subnet_test.go, subnet/watch.go
Add an option to ignore a lease in WatchLeases.
Backends can pass their own lease so filter out events
related to them.
Fixes #241 and #126
=> Ignore own lease in subnet events

backend/alloc/alloc.go, backend/awsvpc/awsvpc.go, backend/common.go, backend/gce/gce.go, backend/hostgw/hostgw.go, backend/udp/udp.go, backend/vxlan/vxlan.go, main.go, network/backend.go, network/network.go, subnet/config.go
- Use a single copy of ctx and plumb it throughout.
This fixes the left over artifact that ctx went into
flannel in stages.
- Backends being responsible for lease renewal is
not really valuable and just leads to duplication.
=> Refactoring: single ctx and pull out LeaseRenewer

remote/client.go
Due to code reorg, the config must now be parsed via
subnet.ParseConfig in remote client.
=> Bug fix: remote mode errors out with bad backend type

backend/alloc/alloc.go, backend/awsvpc/awsvpc.go, backend/common.go, backend/gce/gce.go, backend/hostgw/hostgw.go, backend/udp/udp.go, backend/vxlan/vxlan.go, network/backend.go, network/network.go
We'd like to implement our multitenant OVS backend with a singleton object to set up and create the OVS bridge (we only need one bridge for all tenant networks) and maintain some host-wide flows.  To decrease the complexity of a singleton backend we can very slightly increase the complexity of non-singleton backends by splitting Init() into:
1) Init() which takes properties that won't ever change (ctx, interface properties, etc)
2) AddNetwork() which tells the backend to actually configure itself for the network
A singleton backend will now only be created once, and have its Init() only called once.  After that, each new Network object will trigger an AddNetwork() call to poke the singleton backend to do whatever it needs to do for the new network.
(once the add/remove networks branch …
=> Add support for singleton backends

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/etcd/client/cancelreq.go, Godeps/_workspace/src/github.com/coreos/etcd/client/cancelreq_go14.go, Godeps/_workspace/src/github.com/coreos/etcd/client/client.go, Godeps/_workspace/src/github.com/coreos/etcd/client/client_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/keys.go, Godeps/_workspace/src/github.com/coreos/etcd/client/keys_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/members_test.go, Godeps/_workspace/src/github.com/coreos/etcd/client/srv_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/pathutil/path.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/pathutil/path_test.go, subnet/etcd.go, subnet/mock_registry.go
The first patch fixes up my previous network watching stuff, where the testcases didn't quite match actual etcd behavior and thus the code was also slightly wrong.
The second patch I have questions on... When the etcd client got switched to etcd/client, it broke cancel handling. Because etcd/client returns ClusterError objects from its HTTP methods, those get passed down to registry.go and etcd.go, and then stuff like:
case err == context.Canceled, err == context.DeadlineExceeded:
doesn't work because 'err' is a ClusterError, not a context error. How should this get fixed? I had a couple approaches:
1) strip ClusterErrors in registry.go and return only the first internal error; but this doesn't work because etcd.go checks for etcd.Error too.
2) strip ClusterErrors in etcd.go and return …
=> etcd node and error return handling fixups

backend/vxlan/vxlan.go, network/network.go
VXLAN should fail RegisterNetwork call as
outer code does the retrying. This causes
SIGINT to be properly processed.
=> Better handling of Ctrl+C

remote/server.go
When running flannel with -listen option, systemd service is not notified and 'systemctl start flannel' does not return. Adding daemon.SdNotify("READY=1") to RunServer notifies systemd and the command returns.
The correct place for notifying the systemd is line 278 of remote/server.go [1]. It is the line where a listener is created and the execution is just before the server can start listening for incoming requests.
[1] https://github.com/coreos/flannel/blob/master/remote/server.go#L278
=> Notify systemd service when server is ready to listen

network/ipmasq.go
Traffic coming from host might have src address not of
flannel interface but of some other one. This happened
in conjunction with REDIRECT rules. Masquerade will
force the src addr to be that of the flannel interface.
Fixes #318
=> Masquerade host to flannel traffic.

remote/remote_test.go
1.5 handles connection refused slightly differently (probably
by using SO_ERROR) that needed adjustment to code that detects it.
=> Go 1.5 compat change

main.go, network/manager.go
In a cluster the master flannel or etcd might not be up yet when
flanneld starts, so periodically retry getting initial networks
instead of failing hard.
=> Periodically retry getting initial networks

network/network.go, remote/client.go, remote/server.go, subnet/local_manager.go, subnet/mock_registry.go, subnet/registry.go, subnet/subnet.go, subnet/subnet_test.go
This adds ability to add and remove reservations
for subnet allocations. A subnet is reserved with
the host IP (PublicIP). flannel will then use this
subnet for a host requesting a subnet.
Reservations are denoted in etcd as subnets with no
expiration (TTL is zero). When a reserved subnet is
allocated, it's TTL continues to be not set. If a
reservation is removed, the TTL is set to the usual
24 hours.
Also adds corresponding client/server APIs for
reservation management.
Fixes #280
=> Add reservations to admin control subnet allocs

subnet/local_manager.go, subnet/mock_etcd.go, subnet/mock_etcd_test.go, subnet/registry.go, subnet/registry_test.go
Main motivation here was making sure that the "subnet" and "network" don't get switched around in registry.go any more.  I chose to re-implement a mock etcd since I wasn't sure if flannel testing could necessarily spin up its own etcd on all configurations.
=> Add mock etcd and etcd-backed registry testcases

main.go, subnet/registry.go
Adds support for `--etcd-username` and `--etcd-password` args.
=> Add cli args for etcd basic auth

Documentation/aws-vpc-backend.md
The biggest advantage of using Flannel AWS-VPC backend is that the AWS knows about that IP. That makes it possible to setup ELB to route directly to that container.
=> DOCS: Add note to AWS docs about why it might be used

README.md, network/ipmasq.go
Using ACCEPT means that no other rules in the POSTROUTING chain can
fire. Using RETURN allows other rules to be run (but relies on default
being ACCEPT which is the norm)
=> Remove race-condition when setting up masquerade rules

README.md, backend/vxlan/device.go, backend/vxlan/vxlan.go, glide.lock, glide.yaml, vendor/github.com/vishvananda/netlink/addr_linux.go, vendor/github.com/vishvananda/netlink/filter_linux.go, vendor/github.com/vishvananda/netlink/handle_linux.go, vendor/github.com/vishvananda/netlink/handle_test.go, vendor/github.com/vishvananda/netlink/link_linux.go, vendor/github.com/vishvananda/netlink/link_test.go, vendor/github.com/vishvananda/netlink/nl/nl_linux.go, vendor/github.com/vishvananda/netlink/nl/xfrm_state_linux.go, vendor/github.com/vishvananda/netlink/nl/xfrm_state_linux_test.go, vendor/github.com/vishvananda/netlink/route_linux.go, vendor/github.com/vishvananda/netlink/route_test.go, vendor/github.com/vishvananda/netlink/xfrm_state.go, vendor/github.com/vishvananda/netlink/xfrm_state_linux.go, vendor/github.com/vishvananda/netlink/xfrm_state_test.go
Linux versions 4.0 and above include Group Based Policy support in VXLAN.  This patch provides a GBP config option for the flannel VXLAN backend and bumps the vendored netlink library to include a fix for GBP support.
References
- [VXLAN GBP RFC](https://tools.ietf.org/html/draft-smith-vxlan-group-policy-02)
- [GBP support in Linux 4+](https://github.com/torvalds/linux/commit/3511494ce2f3d3b77544c79b87511a4ddb61dc89)
cc: @rosenhouse @dbellotti @jaydunk
=> Support VXLAN GBP

network/manager.go
`fmt.Errorf` should have a directive to print out ipaddr.
=> Fix a typo in format error.

subnet/mock_etcd_test.go, subnet/registry.go
To avoid odd situation of flannel not reusing last lease
upon restart, flannel should use quorum=true when reading
from etcd to get linearizability.
Fix #383
=> Support quorum read option

Makefile
It causes problems with the gce backend and I believe it's hitting
this bug https://sourceware.org/bugzilla/show_bug.cgi?id=19341
=> Makefile: Disable static builds of flanneld

README.md
On current docker version the command in docs doesn't run.
Original: https://xelatex.github.io/2015/10/10/Flannel-for-Docker-Overlay-Network/
=> The docker daemon syntax change addressed

Makefile, dist/functional-test.sh
This script is the first cut at getting end-to-end testing
for flannel. It brings up etcd in a container and then 2 flannel
instances (also in containers). It then pings one flannel instance
from another. It does this for each of the three backends being
tested: udp, vxlan, host-gw.
To run the script, use "make e2e-test"
=> Add functional (end-to-end) testing

backend/manager.go
various backends call backend.Register, which will log a message.
because Register is called in init() functions before main() runs,
glog's 'logtostderr' flag is not set yet, so glog attemps to create log
files in $TMPDIR. this directory doesn't exist in the new busybox base
image, and we don't want to write log files anyway.
=> backend: do not log in Register

backend/awsvpc/awsvpc.go
This fixes aws-vpc when the route table has [vcp-endpoints](https://docs.aws.amazon.com/AmazonVPC/latest/UserGuide/vpc-endpoints.html)
```
I1002 09:31:59.577237    5056 main.go:132] Installing signal handlers
I1002 09:31:59.577499    5056 manager.go:133] Determining IP address of default interface
I1002 09:31:59.577828    5056 manager.go:163] Using 10.0.1.173 as external interface
I1002 09:31:59.577899    5056 manager.go:164] Using 10.0.1.173 as external endpoint
I1002 09:31:59.690117    5056 local_manager.go:134] Found lease (10.5.30.0/24) for current IP (10.0.1.173), reusing
I1002 09:31:59.693114    5056 local_manager.go:134] Found lease (10.6.105.0/24) for current IP (10.0.1.173), reusing
I1002 09:31:59.987196    5056 awsvpc.go:100] RouteTableID not passed as config parameter, …
```
=> aws-vpc: Fix crash when route has vpc-endpoints

Documentation/kube-flannel.yml
@tomdee This makes it possible to run this flannel daemonset on other architectures as well, thanks!
Just `curl -sSL <url> | sed "s/amd64/arm/" | kubectl apply -f -` and you're done!
Can you merge this please so we can use it with kubeadm please?
=> Fix the kube-flannel.yaml in order to work

subnet/kube/kube.go
- Emit add/remove events to the subnet handler rather than using periodic snapshots.
- This resolves an issue where snapshots would not evaluate changes to the MAC address in the lease. This remains an issue, but we do not need to use snapshots initially, and this PR changes to using events. Filed issue: https://github.com/coreos/flannel/issues/563 to track - as we might want to use snapshots eventually if we want to reset the state periodicially.
- Wait for informer cache to sync so we're not acting on partial/empty state
- We were updating a cached node object in-place, then calling an update via API. If the update failed, it would have left the cached object mismatched from actual state in API. Instead, operate on a copy of the cached object to remove this concern.
=> Improve kube subnet lease handling

backend/vxlan/device.go, backend/vxlan/network.go
As discussed in #427, vxlan logs can be too verbose. With current glog usage, it's not possible to reduce log level, it logs to stderr, and when logging to stderr, everything is logged. Everything is logged unless verbosity levels are used. This PR adds verbosity levels to vxlan Info logs, so they can be enabled when debugging some problem.
=> vxlan logging verbosity

README.md, network/manager.go, network/network.go
This adds the command-line flag `--subnet-lease-renew-margin`, specified as
a number of minutes, instead of relying on the hard-coded default of 1h.
=> Add a flag to configure the subnet lease renewal margin.

dist/functional-test.sh
e.g.
BACKEND=vxlan make e2e-test
to run just the vxlan tests
=> e2e: Allow the backend list to be overridden

backend/vxlan/device.go
Use a /32 netmask for the vxlan device. This avoids the kernel programming
broadcast routes (which won't work).
Unicast routes are already explicitly programmed so there's no need to
use a broader netmask.
=> backend/vxlan: Set the netmask of the IP used for the vxlan device

pkg/ip/ipnet.go
During test case execution, we came across all test case failues due to invalid IP.s generation for s390x system. On checking git issues , we came across the link  https://github.com/coreos/flannel/issues/526, which logs similar issue for bigEndiane during IP.s generation.
On analysis we came across littleEndian check, where code is manipulating IP.s for bigEndianess, which is unnecessary because changes are required only at bit-level not for IP. We are removing the littleEndian check where the IP address are involved.
For example subnetSize := ip.IP4(1 << (32 - cfg.SubnetLen)), assume cfg.SubnetLen=24 (by default) then, value of subnetSize should be same regardless of endianess, which is achieved after endiness check is removed.
=> Modifying pkg/ip/ipnet.go to fix endian problem

Documentation/kube-flannel-rbac.yml, Documentation/kube-flannel.yml
This PR adds RBAC support.
@liggitt
=> Add Kubernetes RBAC support

Documentation/kube-flannel.yml
It would help for quick scripting on dev/test environments and other architectures.
For instance the [following instructions](https://github.com/luxas/kubernetes-on-arm#set-up-the-master) are currently broken since https://github.com/coreos/flannel/commit/ee52b531b0c3ce81b3a08bc3a5dccf4d31476ecd.
=> [doc][kube-flannel] set explicit arch on daemonset images

backend/vxlan/device.go, backend/vxlan/network.go, backend/vxlan/vxlan.go
Rename variables to make them more verbose.
This commit has no functional changes
=> backend/vxlan: Make variables more verbose

backend/vxlan/device.go
Stop deleting IP addresses from the vxlan device, there's no need to do
it and it disrupts traffic during daemon restart.
=> backend/vxlan: Don't recreate vxlan device on flanneld restart

Documentation/kube-flannel-rbac.yml
There is no need to execute two commands (more error prone). The RBAC file is short enough to do it in one step
=> Simplify rbac creation process

Documentation/kube-flannel.yml
DaemonSets now respect taints. This PR adds a tolerance that allows flannel to run nodes tainted with `dedicated=master:NoSchedule`
=> Tolerate flannel running on master nodes

Documentation/kube-flannel.yml
The operator field default to Equals.
We want to schedule flannel to any nodes with node-role.kubernetes.io/master taint regardless of what value was set (which will usually be 'true').
Adding this line allows the DS to schedule flannel pods to master nodes.
=> Explicit operator: Exists to allow toleration on masters

Makefile
The current makefile variable 'PWD' is not defined in the makefile,
and leads to build errors.  Use $(shell pwd) instead.
Fixes errors like these:
docker: Error response from daemon: Invalid volume spec ":/go/src/github.com/coreos/flannel:ro"
=> Makefile: Use $(CURDIR)

Makefile
THe dep has changed now that we build tar.gz file all architectures
=> Makefile: Fix the releases target

.gitignore, Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, Documentation/kube-flannel-rbac.yml, Makefile, subnet/kube/kube.go
=> switch kube subnet manager to PATCH

.gitignore, Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, Makefile
THis means we're now using a newer version of go and
arm-linux-gnueabihf-gcc instead of arm-linux-gnueabi-gcc
=> Makefile: Switch to a new version of kube-cross

bill-of-materials.json, bill-of-materials.override.json, dist/bill-of-materials.sh
CoreOS projects are adding a machine parsable license file. The tool is
from https://github.com/coreos/license-bill-of-materials
=> bill-of-materials: initial commit

README.md
I've added Tom's notes from issue #672
=> Flannel ReadMe: Added Tom's notes.

Documentation/alicloud-vpc-backend.md, Documentation/aws-vpc-backend.md, Documentation/backends.md, Documentation/building.md, Documentation/configuration.md, Documentation/gce-backend.md, Documentation/reporting_bugs.md, Documentation/running.md
Please add content as necessary. In particular, there's some placeholder text in running - "Zero-downtime restarts - moves to an upgrade section (or standalone doc) with extra k8s content"
=> flannel-docs: Updating flannel Documents files.

Documentation/aws-vpc-backend.md, backend/awsvpc/awsvpc.go, main.go, subnet/kube/kube.go
Resolving conflicts for pull request #561 and adding documentation.
This change adds the option of the RouteTableID being passed as an array instead of a
string, allowing multiple route tables to be specified.
=> aws-vpc: add support for multiple route tables

Dockerfile.amd64, Documentation/extension.md, backend/extension/extension.go, backend/extension/extension_network.go, dist/extension-hostgw, dist/extension-vxlan, dist/functional-test.sh, main.go
The `extension` backend provides an easy way for prototyping new backend types for flannel.
It is _not_ recommended for production use, for example it doesn't have a built in retry mechanism.
This backend has the following configuration
* `Type` (string): `extension`
* `PreStartupCommand`  (string): Command to run before allocating a network to this host
* The stdout of the process is captured and passed to the stdin of the SubnetAdd/Remove commands.
* `PostStartupCommand`  (string): Command to run before allocating a network to this host
* The following environment variable is set
* SUBNET - The subnet on the remote host that was added.
* `SubnetAddCommand`   (string): Command to run when a subnet is added
* stdin - The output from `PreStartupCommand` is passed in.
* The following …
=> backend/extension: Introduce new extension backend

subnet/kube/kube.go
=> Allow more events to be buffered before the backend starts

Documentation/configuration.md, main.go
Fix #616 
This PR will add a `healthz` endpoint in http for flanneld by default in `0.0.0.0:8285`.
Note: This PR is based on #632 .
/cc @eyakubovich @tomdee @zbwright
=> add healthz

Makefile
Use Go 1.8.x
Strip the binary
Improvement is ~50MB -> ~30MB
Fixes #674
=> Makefile: Smaller flanneld binary

backend/vxlan/device.go
vxlanLinkIncompat function did not check GBP so it was possible that
changes in the config would not be refreshed.
Fixes #562
=> Added compatibility check to compare GBP for VXLAN

main.go, network/ipmasq.go
This fixes a bug that was preventing OnlyLocal annotation in Kubernetes
from working correctly. Prevents masquerade on external traffic to
containers/pods in the subnet.
Fixes #734
=> Add iptables rule to prevent masquerade on some external traffic

Documentation/configuration.md, main.go
Allows for more flexibility when selecting the network interface that
flannel should be using.
Addresses #620
Ran flannel locally and set the `iface-regex` flag to various regex expressions to check if they match (or do not match) with any of the network interfaces on the machine.
=> Added iface-regex option

main.go
Fixes a bug that prevented iface-regexes from ever returning a proper interface.  Bug was introduced with https://github.com/coreos/flannel/pull/754
=> Fix a bug with the iface-regex that always returned an error

subnet/etcdv2/local_manager.go
Previously leased subnets were not reused properly so in the case that there was a subnet config file created from a previous run, the code would try to recreate that lease even if it already existed within etcd.  This fix allows leases that match the previously leased subnet to be reused even if information about it changes (like the public ip address)
Bug introduced by https://github.com/coreos/flannel/pull/752
Fixes #760
- Followed the steps to reproduce in #760
- Followed the steps to reproduce in #760 but instead of specifying public IP, specified different interfaces to use with different IPs
=> Fix a bug where previously leased subnets would not update etcd leases

Documentation/configuration.md
``configuration.md`` contains a broken reference to a line of code. As etcd v2 will be no longer be shipped with Container Linux by June 2018, the reference to the ``go`` const was removed completely. The sentence has been rewritten in the downstream documentation; this PR is updating upstream to match. 
This will only affect the docs.
=> Remove broken reference

Dockerfile.amd64
fix: add ca-certificates
Backend like aws-vpc or ali-vpc call https IaaS API will failed without ca-certificates.
=> add ca-certificates

main.go
when the subnet-lease-renew-margin is large than 1440(minutes), etcdv2
subnet manager would keep renew lease, causing high CPU load to flanneld
and etcd.
=> Add flag validation for subnet-lease-renew-margin

backend/hostgw/hostgw_network.go
Bug fix for the hostgw backend.
We noticed (#801) that the Flannel was not replacing routes when new nodes were added to the cluster: we saw these error messages in our production cluster
```
[network.go:83] Subnet added: 10.32.10.0/24 via 10.68.29.72\n","stream":"stderr","time":"2017-08-29T17:00:21.968055987Z"}
[network.go:106] Replacing existing route to 10.32.10.0/24 via 10.68.26.131 with 10.32.10.0/24 via 10.68.29.72.\n","stream":"stderr","time":"2017-08-29T17:00:21.968211104Z"}
[network.go:108] Error deleting route to 10.32.10.0/24: no such process\n","stream":"stderr","time":"2017-08-29T17:00:21.96826321Z"}
```
This was happening when an existing route was being replaced with a new route.
This turns out to be for 2 reasons:
1. The wrong LinkIndex was being set on the netlink …
=> Fix route deletion when replacing route in hostgw backend

Documentation/backends.md, backend/vxlan/device.go, backend/vxlan/vxlan.go, backend/vxlan/vxlan_network.go, dist/functional-test.sh
This skips vxlan encapsulation if the hosts are on the same subnet
=> backend/vxlan: Add support for "direct routing"

Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - Fixes #812
This contains following modifications
1. Use supported arm images as baseimage in the dockefiles
2. Remove copying of libraries which is not necessary now, because latest busybox contains all the dependent libs.
=> Remove Library copy commands from dockefiles

.gitignore, Makefile
The Dockerfiles used to need some custom libs. They don't anymore
=> Makefile: Stop pulling the unused lib from kube-cross

Makefile, main.go, network/ipmasq.go, network/ipmasq_test.go
We ran into an issue where sometimes the iptables masquerade rules that flannel creates get deleted. Obviously ideally this wouldn't happen, but if it *does* happen it's really bad -- containers can't send packets to any hosts outside the cluster.
This PR makes flannel automatically recover from this situation by recreating the iptables rules, so that the cluster will remain healthy:
* added a goroutine that automatically recreates the masquerade rules every second
* added an alternate version of `AppendUnique` which returns whether or not the rule was appended. This allows flannel to only log when a rule was actually successfully added, instead of always logging (which, now that we're retrying every second, would add too much noise to the logs)
We're running this in our production …
=> Ensure that the iptables masquerade rule is always installed

Documentation/kube-flannel.yml
it's odd having a container that only does copy and sleep. it made sense when there's no support for initializing pods, but since kubernetes 1.6, init containers became GA, so the flannel daemonset should be able to leverage this to make the pod more clean.
=> use init container to install cni on flannel daemonset

backend/vxlan/device.go
`%#v` is more readable than `%s`.
%s generate error like:
```
&{{%!s(int=0) %!s(int=0) %!s(int=0)   0 %!s(uint32=0) %!s(int=0) %!s(int=0) <nil>  %!s(*netlink.LinkStatistics=<nil>) %!s(int=0) %!s(*netlink.LinkXdp=<nil>)  <nil> unknown} %!s(int=0) %!s(int=0) <nil> <nil> %!s(int=0) %!s(int=0) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(bool=false) %!s(int=0) %!s(int=0) %!s(int=0) %!s(int=0) %!s(int=0)}
```
while %#v:
```
&netlink.Vxlan{LinkAttrs:netlink.LinkAttrs{Index:0, MTU:0, TxQLen:0, Name:"", HardwareAddr:net.HardwareAddr(nil), Flags:0x0, RawFlags:0x0, ParentIndex:0, MasterIndex:0, Namespace:interface {}(nil), Alias:"", Statistics:(*netlink.LinkStatistics)(nil), Promisc:0, Xdp:(*netlink.LinkXdp)(nil), EncapType:"", …
```
=> Fix printf verb %s of wrong type

network/ipmasq.go
Signed-off-by: sakeven <jc5930@sina.cn>
bug fix.
`fmt.Errorf("failed to check rule existence", err)` missed ": %v"。
No formatting directive in Errorf call.
=> Fix error message in ipmasq

.gitignore, Makefile, dist/functional-test-k8s.sh, dist/functional-test.sh
- Move to using bash_unit
- Test pings in both directions
- Test kubernetes subnet manager
- Test multiple versions of etcd and k8s during a release
=> Improve functional tests

Makefile, dist/functional-test-k8s.sh, dist/functional-test.sh, images/iperf3/Dockerfile, images/iperf3/Makefile
This PR is for enabling e2e tests to run on different architectures like arm64 and ppc64le
Can be run on ppc64le platform like below:
```shell
$ make e2e-test ARCH=ppc64le
```
=> Add support for multiarch e2e tests

Documentation/kube-flannel.yml
Hairpin mode is needed to allow pods to communicate with themselves via
Service IP. This change is required as the kubelet --hairpin-mode flag
is not supported when CNI is being used.
This patch is picked from https://github.com/coreos/tectonic-installer/pull/1640
I verified it on K8S 1.7.5 + Flannel vxlan backend, it works as expected.
=> kube-flannel-cfg: enable hairpin mode

dist/functional-test-k8s.sh, dist/functional-test.sh
While running these tests in docker containers I was facing following error:
```
the input device is not a TTY
```
Usually container will not have a TTY and in many places we are trying to run with tty which is not really required, so this PR is submitted for removing such tty option from docker commands.
=> Fix TTY error while running e2e tests in container

.github/PULL_REQUEST_TEMPLATE.md
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
=> Comment out the PR template message and add release note section

README.md
Link to kubernetes documentation was broken (wrong capitalization).
Type of fix: documentation. Just a simple typo fix in the README in the git root to fix the link to the kubernetes docs.
=> README.md: fix link to kubernetes documentation

.gitignore, Makefile
Stop building ACIs
ACIs are no longer built during releases
=> Makefile: Stop building ACIs

.travis.yml
Travis was running the tests twice. They only need to run once
=> travis: Only run the tests once

Documentation/kubernetes.md, dist/functional-test-k8s.sh, subnet/kube/kube.go
This PR fixes #712 by allowing to overwrite the public ip of  a Kubernetes node via the `flannel.alpha.coreos.com/public-ip-overwrite` annotation.
Can anyone point me to the appropriate place for docs, is it just `Documentation/Configuration.md`?
Right now the other annotations aren't documented in this repo.
=> Fix #712, allow overwriting the public IP of a Kubernetes node

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
`MAINTAINER` command has been deprecated (https://docs.docker.com/engine/reference/builder/#maintainer-deprecated), recommended resolution is using `LABEL`
=> MAINTAINER is deprecated, using LABEL now

main.go, network/ipmasq.go, network/ipmasq_test.go
As requested in #832 , we're breaking up the changes into smaller commits.  This PR moves the Setup, monitoring, and teardown of IPMasq settings into platform-specific files.  This is one of the requirements to get Flannel to build on Windows.
From the original PR (#832):
> The goal is to enable users to provision a Kubernetes cluster with windows nodes in VXLAN mode or mixed windows and Linux nodes in host-gw mode.
=> network: move ipmasq management into platform-specific files

.gitignore, Makefile, dist/functional-test-k8s.sh, dist/functional-test.sh
This PR will fix following things:
- Copy the qemu binaries for e2e-test target
- Remove redundant make targets
- Disable the udp tests for non-amd64 architectures
- Gitignore `dist/here.txt` file
=> Fix e2e tests for non-amd64 archs

Documentation/backends.md
They'll raise it if you ask! As written, it is made to sound like a 
permanent unfixable limit.
=> [DOC] Clarify GCE route quota is only 100 by default

subnet/kube/kube.go
Fixes missing logging mentioned in #712
=> Log kubernetes public ip override

Documentation/troubleshooting.md, main.go, network/iptables.go, network/iptables_test.go
To work around the Docker change from v1.13 which
changed the default FORWARD policy to DROP.
The change has bitten many many users.
The troubleshooting documentation is also updated talk about the issue.
Replaces PR #862
Fixes #834
Fixes #823
Fixes #609
Fixes #799
=> network/iptables: Add iptables rules to FORWARD chain

Documentation/kube-flannel.yml, README.md
The portmap plugin is needed for hostPorts to work
The CNI [portmap capability was added in k8s 1.7](https://github.com/kubernetes/kubernetes/issues/23920#issuecomment-306543120). I was able to get past the issue by using the updated kube-flannel.yml on a 1.8.3 cluster.
Closes: https://github.com/coreos/flannel/issues/887
```release-note
None required
```
=> Add portmap plugin to CNI conf

Documentation/k8s-manifests/kube-flannel-legacy.yml, Documentation/kube-flannel-aliyun.yml, Documentation/kube-flannel.yml, Documentation/minikube.yml
Usually flanneld consumes 5m CPU and 15Mi memory according to "kubectl top".
A few sentences describing the overall goals of the pull request's commits. 
Please include 
- the type of fix - (e.g. bug fix, new feature, documentation)
- some details on _why_ this PR should be merged
- the details of the testing you've done on it (both manual and automated)
- which components are affected by this PR
Flannel pod gets default QoS class "BestEffort" when it doesn't specify cpu and memory resources,
this makes its oom_score_adj to be 1000 and thus is more likely killed first when free memory isn't enough.
This patch assigns same amount of  cpu/mem request and amount, makes Flanneld pod gets QoS class "Guaranteed" and oom_score_adj -998 as described at …
=> make sure flanneld got QoS class "Guaranteed" to have lower oom_score_adj

subnet/etcdv2/local_manager.go
Print "None" instead of 0.0.0.0/0 if there's no previous subnet to use
Fixes #767
=> subnet/etcdv2/local_manager.go: Fix startup log

backend/vxlan/device.go, backend/vxlan/vxlan_network.go
Ensure that the correct MTU is being used for vxlan
Fixes #841
=> backend/vxlan: Return correct MTU value

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, backend/extension/extension.go, dist/extension-wireguard, dist/functional-test.sh
This PR adds
- the wireguard tools to the flannel container images (~0.1MB
size increase)
- an example extensions config
- a one-line change to extension.go to pass in the flannel network
The tests are commented out since they won't pass unless the wireguard
kernel module is loaded.
=> backend/extension: Add Wireguard configuration

Documentation/troubleshooting.md
Quick fix to resolve a typo (documentation)
```release-note
None required
```
=> fixes typo

subnet/config.go
Fix all the limits, especially around minimum sizes
Fixes #696
=> subnet/config.go: Fix handling of subnet config

Documentation/troubleshooting.md
- the type of fix : Documentation
kube-flannel-rbac.yml is in k8s-manifests folder.
Documentation/kubernetes.md is already fixed.
but Documentation/troubleshooting.md is not fixed yet. 
so I just fixed Document.
- [O] Documentation
=> Fix invalid url of kube-flannel-rbac.yml

Documentation/configuration.md, main.go, network/iptables.go, network/iptables_windows.go
Referenced issue: https://github.com/coreos/flannel/issues/933
This pull creates a flag that can be used to adjust the resync period of the ensure iptables routine. On a larger cluster with many services we found 5 seconds to be too aggressive and created too much iptables lock contention causing kube-proxy to fail to sync it's tables.
```release-note
Adds new flag --iptables-resync, allows adjustment of IPTables "ensure" check. Expects an integer it will then multiply by seconds, defaults to 5. Guidance is to adjust this upwards if you see too much iptables lock contention.
```
=> Added new flag -iptables-resync

backend/udp/udp_network_amd64.go
I discovered that bug #533 still affects my team, since the fix (#576) only applies to the vxlan backend, but the bug is also present in the udp backend. This pull requests fixes the same bug in the udp backend.
Specifically, I found that whichever host was assigned the zeroth subnet (172.18.0.0/24 out of 172.18.0.0/16 in our test cluster) would not be able to communicate from the host level to the container level of any other host, because the receiving host would think that a message from 172.18.0.0 was from the broadcast address. By changing the flannel interface to have 172.18.x.0/32 bound instead of 172.18.x.0/16, this problem was avoided.
I've deployed these changes to our test cluster, and the problem seems to be resolved without breaking anything else.
Since this is a small …
=> backend/udp: Use a /32 prefix for the flannel0 interface

main.go
I was trying to use the `--iface-regex` and my interface wasn't detected (for a dumb reason. I was adding quotation marks to the argument, and those were added to the string).
At first, I thought this was because my interfaces weren't properly detected by flannel though.
This improves the no detected interfaces error message to show all the available interfaces, name and IP address so it's clearer what the issue could be.
I haven't written tests here because `main.go` doesn't have any, and setting up unit testing seems outside the purpose of this small PR.
```release-note
None required
```
=> Log all the available interfaces when none were found

main.go
This fixes a typo where the arguments parser does not match the usage documentation.
```release-note
None required
```
=> Fixed typo in arguments parser

Documentation/kube-flannel.yml, Documentation/kubernetes.md
This makes it possible to deploy kube-flannel.yml on clusters with multiple architectures without modifications. Fixes #663.
As suggested in [this comment](https://github.com/coreos/flannel/issues/663#issuecomment-335328617), I have added a daemonset for each architecture in `kube-flannel.yml`. Each daemonset will only add pods to nodes with the correct architecture.
A nicer solution (in the future) for this would be to have something like [docker multi-arch manifests](https://blog.docker.com/2017/11/multi-arch-all-the-things/) so that only a single daemonset would be required.
I have only tried this on an amd64 cluster.
```release-note
None required
```
=> Documentation/k8s: add daemonsets for all archs

subnet/kube/kube.go
To fix panic (see log below), add a handler for
cache.DeletedFinalStateUnknown.
```
/usr/local/go/src/runtime/asm_amd64.s:2197
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Node [recovered]
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Node [recovered]
panic: interface conversion: interface {} is cache.DeletedFinalStateUnknown, not *v1.Node
goroutine 19 [running]:
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash(0x0, 0x0, 0x0)
/go/src/github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime/runtime.go:58 +0x126
panic(0x1782360, 0xc420945e80)
/usr/local/go/src/runtime/panic.go:489 +0x2cf
github.com/coreos/flannel/vendor/k8s.io/apimachinery/pkg/util/runtime.HandleCrash( …
```
=> subnet: handle unknown state in delete event

Documentation/kubernetes.md
This adds a link to the `flannel-node-annotator` which automatically sets a `flannel.alpha.coreos.com/public-ip-overwrite` annotation on all Kubernetes nodes that have an `ExternalIP` set.
```release-note
None required
```
=> Add link to flannel-node-annotator

main.go
Fixes https://github.com/kubernetes/kops/issues/4037, https://github.com/projectcalico/canal/issues/115, #938
Add a flag to allow users to specify whether they want to add the default `ACCEPT` traffic rules to the iptables `FORWARD` chain, which was introduced in Flannel release v0.9.1 to support Docker versions 1.13 and later (where docker sets the default policy on the `FORWARD` chain to drop).
Users may need to disable this behaviour in certain scenarios such as documented in #938, where used in conjunction with Calico (when `FELIX_CHAININSERTMODE` is set to `append`), as it breaks network policy behaviour.
**Environment Variable:** FLANNEL_IPTABLES_FORWARD_RULES
**Command Line Option:** iptables-forward-rules
**Default Value:** true (shouldn't break or modify existing behaviour)
=> Make the iptables FORWARD chain rules optional

network/iptables_windows.go
Fixes compilation issues with windows
Was failing local compilation for "make dist/flanneld.exe".  I added the missing functions and it compiles again.
=> Fix windows Build Break

Documentation/configuration.md
Relevant when using --kube-subnet-mgr, e.g. when using the provided Kubernetes manifest.
- type of fix: documentation
- why this PR should be merged: save others from wasting their time dealing with etcd needlessly
```release-note
None required
```
=> Clarify where the config is read from 

main.go, subnet/kube/annotations.go, subnet/kube/annotations_test.go, subnet/kube/kube.go
Fixes https://github.com/coreos/flannel/issues/804
It adds new `--kube-annotation-prefix` flag which defaults to `flannel.alpha.coreos.com` so the current behavior remains unchanged.
=> Allow changing subnet/kube annotation prefix

glide.lock, glide.yaml, network/iptables.go, vendor/github.com/coreos/go-iptables/iptables/iptables.go
This makes Flannel apply a workaround for the infamous Linux conntrack race that causes major problems for many Kubernetes deployments, often manifesting as DNS delays or failures (see https://github.com/kubernetes/kubernetes/issues/56903, https://github.com/weaveworks/weave/issues/3287, https://www.weave.works/blog/racy-conntrack-and-dns-lookup-timeouts and many others).
```release-note
If the underlying iptables binary supports it, use --random-fully when creating MASQ rules
```
=> Use --random-fully when creating MASQ rules

Documentation/troubleshooting.md
Fix a typo in the troubleshooting docs.
I have a little experience with Kubernetes, so `--pod-cidr kubelet` made me think that `kubelet` is the `--pod-cidr` value.
Nothing
```release-note
None required
```
=> Fix a typo: move “kubelet” out of the code block

Documentation/backends.md
doc: Exchange the IPSec `PSK` and `UDPEncap` types to match the implementation
The implementation is: https://github.com/coreos/flannel/blob/62a1314e51047e25606b4e4e30bd23d7a8d746bc/backend/ipsec/ipsec.go#L75-L79
=> doc: Fix wrong type in IPSec description

backend/hostgw/hostgw_windows.go
Fix nil  pointer error where get ManagementIP timeout, and extended get ManagementIP wait time to 30s
Fix issues https://github.com/coreos/flannel/issues/1066
=> Fix nil  pointer error where get ManagementIP timeout

Documentation/kube-flannel.yml
There is a type in the deployment doc that writes the configMap settings to `/etc/cni/net.d/10-flannel.conflist` instead of /etc/cni/net.d/10-flannel.conf` where it needs to be. I noticed this after our HairPin settings were not enabled. After a lengthy investigation I was able to track it down to the Documentation file having an error:
https://raw.githubusercontent.com/coreos/flannel/v0.10.0/Documentation/kube-flannel.yml
If required I can include a more indepth example but from the diff it should be clear there is a typo.
```release-note
None required
```
=> remove "list" typo from daemonset file

Documentation/kube-flannel.yml
Reverts coreos/flannel#1043
As per issue #1082
=> Revert "remove "list" typo from daemonset file"

backend/vxlan/vxlan_windows.go
Gets HNS networks using V2 schema. This removes the redundancy of getting the networks in V1 and then again in V2.
This also fixes an issue users are seeing where a network is listed in the query for V1, but then that network is not able to be found in V2.
```release-note
Updated VXLAN windows to use hcsshim/hcn API entirely instead of hcsshim.
```
=> Use V2 to get networks

Documentation/kube-flannel.yml
looks like 0.11.0 was tagged with 0.10.0 images.
use the 0.11.0 tag as the images are already up:
https://quay.io/repository/coreos/flannel?tab=tags
```release-note
None required
```
=> kube-flannel.yaml: bump images to 0.11.0

Documentation/kube-flannel-old.yaml, dist/functional-test-k8s.sh
Flannel is running in privileged mode, and is using the root user,
therefore if the container is compromised, an attacker will
inherit that level of access. An attacker compromising the flannel
container will have full root access to the host system, and access
to all secrets and containers hosted on the system.
This PR makes sure that flannel runs in unprivileged mode.
This is done by changing the flannel manifests and also adding
a new PSP policy that disables both privilege mode and privilege
escallation.
The new PSP activates 'NET_ADMIN' capability, hostNetwork
and allowedHostPaths.
```release-note
None required
```
=> Deploy Flannel with unprivileged PSP

main.go
This PR adds some additional logging to make the behaviour of flannel more transparent. This can be useful when debugging and looking at the flannel logs. Since these features are optional, it's more clear whether they are enabled or not this way.
```release-note
Additional logging for flannel behaviour during initialisation
```
=> Add additional logging for optional features

subnet/kube/kube.go
function [BuildConfigFromFlags](https://github.com/coreos/flannel/blob/ba49cd4c1e49d566da4a08b370384ce8ced0c0e3/vendor/k8s.io/client-go/tools/clientcmd/client_config.go#L515) will build kubernetes config from masterURL or kubeconfig filepath firstly, if both are empty, it will fall back to build in-cluster config, if fails again, it will fall back to default config. So I think the origin codes for building kubernetes config are redundant and need some clean.
```release-note
None required
```
=> clean redundant code in building kubernetes config

Documentation/configuration.md, main.go, subnet/kube/kube.go
Add the flag "net-config-path" that holds the path
for the network configuration.
Set the default value to "/etc/kube-flannel/net-conf.json".
```release-note
add the "net-config-path" CLI flag (set to "/etc/kube-flannel/net-conf.json" by default)
```
/assign @ksubrmnn 
/area configuration
/kind enhancement
=> main.go: add the "net-config-path" flag

backend/vxlan/device.go, backend/vxlan/vxlan.go
allow user to configure VXLAN device learning attribute
address https://github.com/coreos/flannel/issues/1150
In some use case like BIGIP k8s controller integration with flannel vxlan, k8s node VTEP/POD ARP may needs to be populated on BIGIP as dynamic ARP/FDB record as result of dynamic ARP request/ARP reply mechanism, the learning attribute is required to make it work as tested in lab, thus the pull request to make learning attribute configurable by users.
```release-note
None required
```
=> Make VXLAN device learning attribute configurable

Documentation/kube-flannel.yml
In  the k8s 1.14.0 release notes, there are concrete timelines for deprecated resources in the extensions/v1beta1, apps/v1beta1, and apps/v1beta2 API groups to no longer be served by default.
https://groups.google.com/d/msg/kubernetes-dev/je0rjyfTVyc/gEUw1YcyAQAJ
The flannel installation manifest need to be updated in order to work
```release-note
Update kubernetes deprecated API resources in the installation manifest 
https://github.com/kubernetes/kubernetes/blob/master/CHANGELOG-1.14.md#deprecations
```
=> Update deprecated API resources

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
I made a PR that fixed Dcokerfile missing `wireguard-tools `,so it can't build.
```bash
Step 5/8 : RUN apk add wireguard-tools --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing
---> Running in 8c2c5b2100fe
fetch http://dl-cdn.alpinelinux.org/alpine/edge/testing/x86_64/APKINDEX.tar.gz
ERROR: unsatisfiable constraints:
wireguard-tools (missing):
required by: world[wireguard-tools]
The command '/bin/sh -c apk add wireguard-tools --no-cache --repository http://dl-cdn.alpinelinux.org/alpine/edge/testing' returned a non-zero code: 1
```
`wireguard-tools `  has been modified the repository from ` testing `to  `community` 
[alpinelinux pkg query ](https://pkgs.alpinelinux.org/packages?name=wireguard-tools&branch=edge&repo=testing&arch=x86_64)
```release-note
None required …
```
=> Fix up: missing wireguard-tools, build error

Documentation/kube-flannel.yml
Increase the condition so that the flannel pod is not dispatched to the windows node, and the nodeSelector is modified to a more elegant nodeAffinity
```release-note
None required
```
=> change nodeSelector to nodeAffinity and  schedule the pod to linux node

Documentation/kube-flannel.yml
The configuration schema version is required to ensure compatibility.
Some implementations (CRI-O) require the field to be set.
Closes #1173.
The configmap in the general manifest at `./Documentation/kube-flannel.yml` now specifies the `cniVersion`. This makes the CRI-O error described in #1173 disappear.  
Please note that the following files also don't specify the `cniVersion` but I left them untouched since I am not sure which version would be appropriate since they are either legacy or for a particular environment which I am not running currently to test it:
* `./Documentation/kube-flannel-aliyun.yml`
* `./Documentation/kube-flannel-old.yaml`
* `./Documentation/k8s-manifests/kube-flannel-legacy.yml`
* `./Documentation/minikube.yml`
=> Add cniVersion to general CNI plugin configuration.

Documentation/kube-flannel.yml
kubernetes 1.16   cni install error
``` shell
kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/32a765fd19ba45b387fdc5e3812c41fff47cfd55/Documentation/kube-flannel.yml
```
https://github.com/kubernetes/kubeadm/issues/1799
=> kubernetes 1.16 cni error

Documentation/k8s-manifests/kube-flannel-legacy.yml, Documentation/kube-flannel-aliyun.yml, Documentation/kube-flannel-old.yaml, Documentation/kube-flannel.yml, Documentation/minikube.yml
This PR adds the cni version to the cni-conf.yaml inside the kube-flannel-cfg configmap
This PR fixes an issue we latest multus version.
Multus is unable to call the cni delete function because the cni version is not configured.
Because of this issue pod addresses are not released
Error from pod:
```
Warning  FailedKillPod  8s     kubelet, node01    error killing pod: failed to "KillPodSandbox" for "cca49d68-758d-11e9-b08c-525500d15501" with KillPodSandboxError: "rpc error: code = Unknown desc = NetworkPlugin cni failed to teardown pod \"pod-example_default\" network: Multus: error in invoke Conflist Del - \"cbr0\": error in getting result from DelNetworkList: failed to convert major version part \"\": strconv.Atoi: parsing \"\": invalid syntax"
```
```release-note
None required
```
=> add cni version to cni-conf yaml

backend/vxlan/device_windows.go
This PR adds the EnableNonPersistent flag for Windows Overlay networks. This ensures that the network will be cleaned up upon reboot. 
```release-note
NONE
```
=> EnableNonPersistent flag for Windows Overlay networks

dist/functional-test.sh
- bug fix
- e2e-tests teardown
If you look into the output of iperf after running e2e-tests ([travis](https://travis-ci.org/coreos/flannel/builds/593646073)) you'll notice that ipsec is fast and vxlan is slow. I inspected this further and noticed that an e2e-test is always using the network config of the previous test. The tests assuming that flannel waits until etcd is written. But because the old network config is not removed flannel starts using that configuration. This PR fixes this behaviour and removes etcd network config after each test is run.
```release-note
None required
```
=> Fix: prevent e2e tests to reuse network config of previous tests

Documentation/kube-flannel.yml, Makefile, dist/functional-test-k8s.sh, dist/functional-test.sh, subnet/etcdv2/mock_etcd.go
- Clean up the test harness to run latest kube versions (both pre 1.16 and post 1.16)
- Changes to etcd tests to be compatible with hosts that have DNS search domains
- Modify the Documentation/kube-flannel.yml so that latest release images are matched
```release-note
None required
```
=> Spruce up for release 12.0

Documentation/kube-flannel.yml
```release-note
beta.kubernetes.io/os deprecated since v1.14, are targeted for removal in v1.18
```
We can know from  https://kubernetes.io/docs/reference/kubernetes-api/labels-annotations-taints/
https://github.com/kubernetes/kubernetes/issues/89477
=> Use stable os and arch label for node

Documentation/backends.md, backend/awsvpc/awsvpc.go
The awsvpc backend requires permission `ModifyNetworkInterfaceAttribute` instead of `ModifyInstanceAttribute`, otherwise flanneld would complain 
```
failed to disable SourceDestCheck on eni-xxx: UnauthorizedOperation: You are not authorized to perform this operation.
```
In addtion, a small typo in `awsvpc.go` is fixed.
```release-note
None required
```
=> doc(awsvpc): correct the required permissions

backend/vxlan/vxlan_windows.go
ISSUE: https://github.com/coreos/flannel/issues/1280
When we deploy flannel `vxlan` on windows and do not use `kubeSubnetMgr`.  We found vtepMac would be reset to "". 
See https://github.com/coreos/flannel/blob/master/backend/vxlan/vxlan_windows.go#L134
VtepMac is nil
See https://github.com/coreos/flannel/blob/master/backend/vxlan/vxlan_windows.go#L139
Acquire lease
See https://github.com/coreos/flannel/blob/master/backend/vxlan/vxlan_windows.go#L161
Create Network
Although https://github.com/coreos/flannel/blob/master/backend/vxlan/vxlan_windows.go#L188, re-acquire the lease. but we have not reset it to the `network` and it returned(mac is nil).
Then, `MonitorLease` would renew lease periodically use the network(mac is nil)
```
// Kube subnet mgr doesn't lease the subnet for this node - …
```
=> Bugfix: VtepMac would be empty when lease re-acquire for windows without kubeSubnetMgr

backend/vxlan/device.go, vendor/github.com/containernetworking/plugins/pkg/utils/sysctl/sysctl_linux.go
This fix is draft variant of disabling accept_ra on the interfaces flannel creates to avoid routes injection.
=> Disabling ipv6 accept_ra explicitly on the container interface

backend/vxlan/device.go
CI Fix
https://github.com/coreos/flannel/commit/8abf12ad0c4ed0853ea6585d99e741cd4b81727b was merged but does not pass the `gofmt` test in CI
```release-note
None required
```
=> Run gofmt -w on backend/vxlan/device.go to pass CI

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, dist/iptables-wrapper-installer.sh
https://github.com/coreos/flannel/issues/1317
This PR implements the `iptables-wrapper-installer.sh` script from https://github.com/kubernetes-sigs/iptables-wrappers/
```release-note
Enable auto-switching between `iptables (nf_tables)` and `iptables (legacy)` in Flannel container image
```
=> Add and implement iptables-wrapper-installer.sh

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, images/iperf3/Makefile
warn report by quay.io :
https://quay.io/repository/coreos/flannel/manifest/sha256:6d451d92c921f14bfb38196aacb6e506d4593c5b3c9d40a8b8a2506010dc3e10?tab=vulnerabilities
this security issue is not present in 3.11 :
https://github.com/alpinelinux/docker-alpine/issues/34
fix CVE-2019-14697
```release-note
use a recent alpine version with secure musl lib (CVE-2019-14697)
```
=> fix CVE-2019-14697

Documentation/kube-flannel.yml
cri-o drops NET_RAW capability by default, so flannel container is not able to self-set its iptables rules.
Adding NET_RAW capability allows flannel to become compatible with k8s using cri-o as runtime.
Otherwise, the pods remain looping in iptables rules creation.
Solves:
coreos#1300
=> Add NET_RAW capability to support cri-o

Makefile
Multi-arch Docker images are very common these days and allow simplify Kubernetes manifests and deployments in general.
At the moment, flannel publishes the AMD64 image both as $REPO:$TAG and $REPO:$TAG-amd64. Instead of duplicating the AMD64 image, the $REPO:$TAG could be a Docker manifest.
This would allow to de-duplicate a lot the content of https://github.com/coreos/flannel/blob/v0.12.0/Documentation/kube-flannel.yml in a future PR.
Fixes: #1116 
```release-note
Create multi-arch image instead of duplicating the AMD64 image
```
=> Use "docker manifest" to publish multi-arch Docker images

Documentation/kube-flannel.yml
This simplifies the main Kubernetes manifest to use the multi-arch Docker images proposed in https://github.com/coreos/flannel/pull/1327.
I am assuming the new images will be tagged as `v0.12.1`, but can be easily changed. 
```release-note
Simplify the Kubernetes manifest by using the multi-arch image instead of duplicating DaemonSets
```
=> Use multi-arch Docker images in the Kubernetes manifest

Documentation/kubernetes.md
This commit fixes expired URL link pointing to how to deploy Flannel with kubeadm in Documentation/kubernetes.md .
```release-note
None required
```
=> Fix Expired URL to Deploying Flannel with kubeadm

Documentation/kube-flannel.yml, Documentation/kubernetes.md, README.md
**[Type of fix] :** Bug
This commit modifies `Document/kube-flannel.yaml` to use `ClusterRole` & `ClusterRoleBinding` of `rbac.authorization.k8s.io/v1`.
Before this commit, `rbac.authorization.k8s.io/v1beta1` is used at `kube-flannel.yaml`. However, from Kubernetes v1.17, this v1beta1 version is [deprecated](https://v1-17.docs.kubernetes.io/docs/setup/release/notes/#deprecations-and-removals) and `rbac.authorization.k8s.io/v1` becomes GA.
At the time of writing this commit, latest Kubernets version is v1.19. So, according to Kubernetes support policy, only v1.19, v1.18 & v1.17 are supported and it's safe to use `rbac.authorization.k8s.io/v1` now.
```release-note
None required
```
=> Modify kube-flannel.yaml to use rbac.authorization.k8s.io/v1

network/iptables.go, network/iptables_test.go
Fixes #1146
The cause of the incorrect order of Flannel's rules in #1146 was found to be a case where an error occurs on deleting a rule and Flannel ignores the error and assumes the rule was already deleted.  As a result, the remaining rules are re-appended after the rule that could not be deleted, possibly causing them to be in the wrong order.  This change stops deleting additional rules on error and waits for the next execution of the reconciliation loop to correct the rules (assuming that the error deleting the rule was transient).
Type: Bug fix
Testing: In addition to the unit test, this has been tested as a patch on 0.9.1 (deployed on Kubernetes 1.13) where I verified that the error message for failing to teardown did get logged and that the rules on that host remained in the …
=> iptables: handle errors that prevent rule deletes

backend/vxlan/vxlan.go, backend/vxlan/vxlan_network.go, backend/vxlan/vxlan_network_windows.go
Windows currently doesn't support any other VNI that 4096. The VNI for the remote should be retrieved from the subnet lease and set in the Policies of the vxlan HNS-Network. However, on Linu, flannel does not include the VNI in the Lease Attributes.
=> Use remote VNI for Windows

Documentation/troubleshooting.md
flanneld start failed while passing `--iface eth1` flag, and start success with `--iface=eth1` flag
```sh
kubectl logs -f kube-flannel-ds-amd64-hhmgf -n kube-system 
```
The error logs is list as following:
```
flag provided but not defined: -iface eth1
Usage: /opt/bin/flanneld [OPTION]...
-etcd-cafile string
SSL Certificate Authority file used to secure etcd communication
-etcd-certfile string
SSL certification file used to secure etcd communication
-etcd-endpoints string
a comma-delimited list of etcd endpoints (default "http://127.0.0.1:4001,http://127.0.0.1:2379")
-etcd-keyfile string
SSL key file used to secure etcd communication
-etcd-password string
password for BasicAuth to etcd
-etcd-prefix string
etcd prefix (default "/coreos.com/network")
-etcd-username string
username for …
```
=> fix troubleshooting.md

CONTRIBUTING.md, README.md
Bug fix: Drop mentions of coreos-dev mailing list and Freenode #coreos channel in README and CONTRIBUTING docs, since those communication channels aren't active anymore.
```release-note
None required
```
=> docs: drop obsolete communication channels

subnet/etcdv2/local_manager.go, subnet/watch.go
This PR fixs an issue when flannel gets illegal subnet event in
watching leases, it doesn't move forward the etcd cursor and
will stuck in the same invalid event forever.
As the commit message mentions, in local_manager mode when the "WatchLeases" goroutine gets an invalid subnet event (in detail [function parseSubnetWatchResponse](https://github.com/coreos/flannel/blob/be2cb996dab08c68614a05e3bf30020c0a9fbafc/subnet/etcdv2/registry.go#L228) returns error), it doesn't move the cursor forward to skip this invalid subnet as the error string says.
This PR try to fix the issue.
```release-note
subnets: move forward the cursor to skip illegal subnet
```
=> subnets: move forward the cursor to skip illegal subnet

backend/ipsec/handle_charon.go, backend/ipsec/ipsec.go
Charon ike daemon path is hardcoded according to its install location
in alpine distribution off which is based the flannel image used in
standard kubernetes deployment.
This commit hardcodes other well known paths of charon daemon in
different distributions to improve support in manual execution
scenarios or customized flannel images.
```release-note
None required
```
=> ipsec: use well known paths of charon daemon

Documentation/running.md
Documentation for running flannel used 0.10 version instead of 0.12
```release-note
None required
```
=> Update flannel version in documentation

Documentation/kube-flannel.yml
For release candidate v13.1-rc2
```release-note
60464442 Update vendor with glog to klog change
31dbe1c5 Move from glog to klog
a85e1279 fix(host-gw): failed to restart if gateway hnsep existed
e5a30dae ipsec: use well known paths of charon daemon
e951cf74 client-go version bump
```
=> move tag to 13.1-rc2

backend/extension/extension.go
Commands executed for the extension backend preserve the existing
process environment adding flannel specific variables instead of
replacing the whole environment.
=> Preserve environment for extension backend

backend/ipip/ipip.go, backend/vxlan/device.go, backend/vxlan/vxlan.go, pkg/ip/iface.go, pkg/ip/iface_test.go
Currently flannel interface ip addresses are checked on startup when
using vxlan and ipip backends. If multiple addresses are found, startup
fails fatally. If only one address is found and is not the currently
leased one, it will be assumed that it comes from a previous lease and
be removed.
This criteria seems arbitrary both in how it is done and in its timing.
It may cause failures in situations where it might not be strictly
necessary like for example if the node is running a dhcp client that is
assigning link local addresses to all interfaces. It also might fail at
flannel unexpected restarts which are completly unrelated to
the external event that caused the unexpected modification in the
flannel interface.
This patch proposes to concern and check only ip address within the
flannel …
=> Concern only about flannel ip addresses

backend/hostgw/hostgw_windows.go, backend/vxlan/device_windows.go
Get a nil pointer panic if HCN/HNS failed to query the HostComputeNetwork/HNSNetwork via network id, as the `newNetwork` reference has been overridden with `nil`.
=> fix(windows): nil pointer panic

backend/extension/extension_network.go, backend/ipsec/ipsec_network.go, backend/route_network.go, backend/route_network_windows.go, backend/udp/udp_network_amd64.go, backend/vxlan/vxlan_network.go, backend/vxlan/vxlan_network_windows.go, main.go, subnet/etcdv2/mock_etcd.go, subnet/watch.go
Flannel sometimes hang when lease expired. I checked goroutines, it hangs on https://github.com/coreos/flannel/blob/v0.12.0/subnet/watch.go#L59 .
I can't share the goroutine screenshot because I'm using a modified version of flannel.
```release-note
Fix flannel hang if lease expired
```
=> Fix flannel hang if lease expired

Documentation/running.md
Flannel doesn't need to replace deamon0 network in Docker and does work even if the you create new docker network that uses flannel.
Flannel when using with docker doesn't need to replace the default docker0 network, instead, it can be attached to a new docker network. I have added documentation for this type of workflow.
```release-note
None required
```
=> doc: Add section about creating new docker network

Documentation/kube-flannel.yml
for release candidate v0.14.0-rc1
Key commits:
fdef5949 Add tencent cloud VPC network support
26b1485e moving go modules to flannel-io/flannel and updating to go 1.16
bb5eed1a fix(windows): nil pointer panic
6c0ec9ab Preserve environment for extension backend
78035d0c Fix flannel hang if lease expired
15262f05 Documentation for the Flannel upgrade/downgrade procedure
31dbe1c5 Move from glog to klog
a85e1279 fix(host-gw): failed to restart if gateway hnsep existed
e5a30dae ipsec: use well known paths of charon daemon
ba8c2165 upgrade client-go to 1.19.4
43781301 move from juju/errors to pkg/errors
1a1b6f13 subnets: move forward the cursor to skip illegal subnet
aa2491d5 Fix Expired URL to Deploying Flannel with kubeadm
8a1bcf6f Modify kube-flannel.yaml to use rbac.authorization.k8s.io/v1 …
=> make images point to v0.14.0-rc1

main.go
When looking at the logs, it is impossible to say what values are passed as flags. This patch logs that which will help debugging. The output will be:
```
CLI flags config: {etcdEndpoints:http://127.0.0.1:4001,http://127.0.0.1:2379 etcdPrefix:/coreos.com/network etcdKeyfile: etcdCertfile: etcdCAFile: etcdUsername: etcdPassword: help:false version:false kubeSubnetMgr:true kubeApiUrl: kubeAnnotationPrefix:flannel.alpha.coreos.com kubeConfigFile: iface:[] ifaceRegex:[] ipMasq:true subnetFile:/run/flannel/subnet.env subnetDir: publicIP: subnetLeaseRenewMargin:60 healthzIP:0.0.0.0 healthzPort:0 charonExecutablePath: charonViciUri: iptablesResyncSeconds:5 iptablesForwardRules:true netConfPath:/etc/kube-flannel/net-conf.json}
``
```release-note
None required
```
Signed-off-by: Manuel Buil …
```
=> Log all config created using CLI flags

Documentation/configuration.md, backend/common.go, backend/vxlan/device.go, backend/vxlan/vxlan.go, backend/vxlan/vxlan_network.go, go.sum, main.go, network/iptables.go, network/iptables_test.go, pkg/ip/iface.go, pkg/ip/iface_test.go, pkg/ip/ip6net.go, pkg/ip/ip6net_test.go, subnet/config.go, subnet/config_test.go, subnet/etcdv2/local_manager.go, subnet/etcdv2/registry.go, subnet/etcdv2/registry_test.go, subnet/etcdv2/subnet_test.go, subnet/kube/annotations.go, subnet/kube/kube.go, subnet/subnet.go, subnet/watch.go
Add new option for flannel daemon to support dual stack:
- "publicIPv6": "IPv6 accessible by other nodes for
inter-host communication"
Add new option into `net-conf.json` configuration, like following:
{
"EnableIPv4": true,
"EnableIPv6": true,
"Network": "172.16.0.0/16",
"IPv6Network": "fc00::/48",
"Backend": {
"Type": "vxlan"
}
}
EnableIPv4 default value is true for using kube subnet manager.
EnableIpv6 default value is false.
Flannel dual stack feature has limitation, only work with vxlan backend
and kube subnet manager now. To enable flannel dual stack feature, need
to do the following step:
1. setting flanneld daemon with "--kube-subnet-mgr"
2. settting "EnableIPv6" and "IPv6Network" in "net-conf.json" like the
above configuration.
3. setting network interface that flannel used ipv6 …
=> Dual-stack support

backend/alivpc/alivpc.go, backend/alivpc/alivpc_windows.go, backend/awsvpc/awsvpc.go, backend/awsvpc/awsvpc_windows.go, backend/common.go, backend/gce/gce_windows.go, backend/hostgw/hostgw.go, backend/ipip/ipip_windows.go, backend/ipsec/ipsec_windows.go, backend/manager.go, backend/route_network.go, backend/route_network_windows.go, backend/simple_network.go, backend/tencentvpc/tencentvpc_windows.go, backend/udp/udp_amd64.go, backend/udp/udp_network_amd64.go, backend/udp/udp_windows.go, backend/vxlan/vxlan.go, backend/vxlan/vxlan_network.go, backend/vxlan/vxlan_network_windows.go, backend/vxlan/vxlan_windows.go, main.go, network/iptables_windows.go, pkg/ip/iface_windows.go, subnet/etcdv2/mock_registry.go, subnet/etcdv2/registry_test.go, subnet/watch.go, version/version.go
also removes the init func in ipsec for windows to remove unnecessary log if you do an empty import to get the backends initialized.
=> fixing regex logic to get things compiling again, added windows funcs for ipv6 so it compiles

.github/workflows/build.yaml
Signed-off-by: Prabhav Thali <Prabhav.Thali1@ibm.com>
As Travis builds are not getting triggered, Added GH actions workflow which will build Flannel on every PR/commit. Such that the build is verified on every new commit. 
Ref issue : #1456
=> Adds CI build

Documentation/troubleshooting.md
```release-note
None required
```
=> Minor typo in troubleshooting documentation

Documentation/aws-vpc-backend.md
The documentation in this file contained too many braces at the end of this example.
Removed them, so the example can be more easily copy-pasted
=> Removed extra end braces in documentation

Documentation/kube-flannel.yml
This prevents iptables contention with kube-proxy and the host OS.
Fixes #988.
```release-note
Adds /run/xtables.lock mount to kube-flannel.yml to prevent iptables contention with kube-proxy and the host OS.
```
=> Add /run/xtables.lock mount to kube-flannel.yml

.github/workflows/build.yaml, .github/workflows/release.yml, Dockerfile.mips64le, Makefile
The ARCH is mips64le because mipsel is a joke created by Debian. (Because little endian reverse the byte order, they also reversed the letter LE to form el.)
The change version can run successfully by cross-compile. But still need to test because I don't have mips64el environment.
=> rebase add mips64le support

main.go
stop healthz http server cleanly
```release-note
None required
```
=> stop healthz http server cleanly

Documentation/configuration.md, main.go, pkg/ip/ip6net.go, pkg/ip/ip6net_test.go, subnet/etcdv2/local_manager.go, subnet/etcdv2/mock_registry.go, subnet/etcdv2/mock_subnet.go, subnet/etcdv2/registry.go, subnet/etcdv2/registry_test.go, subnet/etcdv2/subnet_test.go, subnet/kube/kube.go, subnet/subnet.go, subnet/subnet_test.go, subnet/watch.go
Add dual-stack support to the etcd registry
```release-note
None required
```
=> Add dual-stack support to the etcd registry

Documentation/configuration.md, main.go, subnet/kube/kube.go
It partially resolves #1453 in case of kube as subnet manager, etcd support is still missing.
IPv4 is always enabled by default to disable it add `"EnableIPv4": false` on the net-conf.json.
```release-note
None required
```
=> Ipv6 only support

network/iptables.go
The d was missing
```release-note
Fix an iptables comment typo
```
=> Fix iptables comment typo

main.go, pkg/ip/iface.go, pkg/ip/iface_windows.go, pkg/ip/iface_windows_test.go, pkg/ipmatch/match.go, pkg/ipmatch/match_test.go
resolve  https://github.com/flannel-io/flannel/issues/981
if interface has multi IPs, current match implementation will failed to get the right IP.
for example, interface `dummy0` has 4 IPs:
```
1.10.100.1
192.168.200.128
172.16.30.18
172.16.31.200
```
we expect to use `192\.168\.200\.\d+` as `--iface-regex` option to get  `192.168.200.128` matched.
```release-note
None required
```
=> feat: add support for --iface-regex match interface with multi IP addresses

Documentation/backends.md, backend/wireguard/device.go, backend/wireguard/wireguard.go, backend/wireguard/wireguard_network.go, pkg/ip/ip6net.go, pkg/ip/ip6net_test.go, pkg/ip/ipnet.go, pkg/ip/ipnet_test.go
Allow users to configure a wireguard backend mode which determines how
the tunnel(s) are setup. The current method (a tunnel per address
family) is kept as a "seperate" mode on top of that three modes are
added that use a single wireguard tunnel overe which traffic for both
network families travels. Specifically the following new modes are
added all using a single tunnel:
* ipv4: Use the remote nodes ipv4 address as wireguard pper
* ipv6: Use the remote nodes ipv6 address as wireguard pper
* auto: automatically determine which remote node address (v4 or v6) to
use. (default)
The main benefit of these new modes is that all combinations of nodes
only need to have a single viable network path between them to setup the
full mesh. For example if in a dual-stack setup (some) nodes have no …
=> Add modes to the wireguard backend to use a single tunnel for both address families

Documentation/configuration.md, main.go, pkg/ip/iface.go, pkg/ipmatch/match.go, pkg/ipmatch/match_test.go
Actually this is similar to Calico's `can-reach=DESTINATION` feature. https://projectcalico.docs.tigera.io/reference/node/configuration#can-reachdestination
maybe background is same, this option is really convenient for the cluster having many kind of nodes.
Actually we're using in production cluster.
Completely new feature, current feature shouldn't be affected.
```release-note
--iface-can-reach is added as new option to decide which interface will be used 
```
=> Add --iface-can-reach option as new way to decide IF

Makefile, README.md, dist/functional-test-k8s.sh, subnet/kube/kube.go, subnet/kube/kube_test.go
Faced issue that `iptables` forwarding rules have been created for the default subnet from the `net-conf.json` config while actual PodCIDR was different.
=> Add validation that PodCIDR(s) matches the network specified in the `net-conf.json`

README.md
It took me ages to figure this out
=> Add note about putting a flanneld binary in /opt/bin

backend/wireguard/device.go, backend/wireguard/wireguard.go, pkg/ip/iface_windows.go
- Fixed MTU for flannel wireguard interfaces to be the same of external interface.
- Added `GetInterfaceBySpecificIPRouting` on windows
```release-note
None required
```
=> Fixed wireguard MTU and added windows iface func

subnet/kube/kube.go
Fix segfault loop if flannel does not have IPv6-cidr in the config.
```shell
I0528 13:35:18.994988       1 vxlan.go:138] VXLAN config: VNI=1 Port=4789 GBP=false Learning=false DirectRouting=false
I0528 13:35:18.995958       1 kube.go:351] Setting NodeNetworkUnavailable
panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x10 pc=0x738dfd]
goroutine 1 [running]:
github.com/flannel-io/flannel/pkg/ip.(*IP6).ToIP(0x0)
/go/src/github.com/flannel-io/flannel/pkg/ip/ip6net.go:82 +0x1d
github.com/flannel-io/flannel/pkg/ip.IP6Net.ToIPNet({0x0, 0xc00015a7b0})
/go/src/github.com/flannel-io/flannel/pkg/ip/ip6net.go:167 +0x27
github.com/flannel-io/flannel/subnet/kube.(*kubeSubnetManager).AcquireLease(0xc000528380, {0x1eb1a18, …
```
=> fix: assign IPv6 `podCIDR` from kubelet spec.

subnet/etcd/local_manager.go
Fix the subnet allocation in case of etcd when using IPv6 #1580 #1581 
```release-note
None required
```
=> Fixed subnet allocation in case of etcd manager with IPv6

backend/route_network_test.go, dist/functional-test.sh
The second gw did not make any sense and that's why we were seeing problems in https://github.com/flannel-io/flannel/issues/1593. This PR fixes that and adds a new check so that the unit test fails if that would happen again
```release-note
None required
```
=> Fix the v6 unit test failing

dist/functional-test.sh
This PR fixes the CI problem as described in https://github.com/flannel-io/flannel/issues/1594. It changes the etcdctl command from "rm" to "del" which is the correct one for v3. Then, it adds -e bash flag to make sure this error or future ones are not ignored
Besides, add `--always` to git describe or it fails
```release-note
None required
```
=> Fix etcd key removal in CI and add -e flag

dist/functional-test-k8s.sh, main.go, network/iptables.go, network/iptables_restore.go, network/iptables_restore_test.go, network/iptables_test.go
Use iptables-restore to preserve order with MASQ & FORWARD rules.
When anything happen when delete/append iptables rules, sometimes you can have your rules out of order.This PR use only iptables-restore to guaranty order in delete/append rules.
This close https://github.com/coreos/flannel/issues/1261 & https://github.com/coreos/flannel/issues/1146
```release-note
None required
```
=> Use iptables-restore to preserve order with MASQ & FORWARD rules

backend/wireguard/wireguard.go
Flannel terminates with segmentation fault if you enable only ipv6 in separate mode.
```release-note
None required
```
=> wireguard: fix segmentation fault if only ipv6 is enabled

main.go, network/iptables_restore_test.go, network/iptables_windows.go, pkg/ipmatch/match.go
Fix #1596 when Public IPv6 is configured the right interface will be selected and no errors occur in case of dualstack.
```release-note
None required
```
=> Public ip dualstack

dist/functional-test.sh
It's fix the issue : https://github.com/flannel-io/flannel/issues/1598
(wait to launch iperf3 test that the container is running)
=> Fix waiting for iperf docker is running before launch test

Documentation/kube-flannel-psp.yml, Documentation/kubernetes.md
The PodSecurityPolicy API will be removed in Kubernetes v1.25 so we use the PodSecurity Admission Controller instead.
The flannel manifest using PodSecurityPolicy is still available as kube-flannel-psp.yaml.
```release-note
None required
```
=> Remove PodSecurityPolicy from kube-flannel.yaml

Documentation/building.md, Documentation/running.md
Updated documentation with right flannel version and docker registry.
Removed CoreOS integration paragraph because CoreOS is not shipped with flannel any more.
```release-note
None required
```
=> Updated documentation

dist/functional-test-k8s.sh, dist/functional-test.sh
Signed-off-by: odidev <odidev@puresoftware.com>
Changing etcd version to 3.51 lets the functional tests pass successfully on ARM64 platform.
=> ADD ARM64 support

Documentation/kubernetes.md
Remove outdated info and fixed typo.
=> doc: update kubernetes.md

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml
Updated yaml file with new image version
=> Updated manifest with v0.19.1

subnet/config.go, subnet/config_test.go
If the user does not include the Network or IPv6Network parameters in the config, flannel fails without a useful error and it often breaks the network of the host. Therefore, we should check that these parameters exist in case ipv4 or ipv6 was enabled
```release-note
```
=> Add a check when reading the config

dist/functional-test-k8s.sh, main.go, network/iptables.go, network/iptables_test.go, network/iptables_windows.go
Added a different chain for Flannel iptables rules to order the rules before the one already present on the node.
It should solve #1619 #1542 #1033
```release-note
None required
```
=> Added a different chain for iptables rules

subnet/kube/kube.go
We're using the `alloc` backend, when the cluster is large like 1000+ nodes, the node informer consumed many resources. So I was thinking about optimize this, it turned out that `alloc` doesn't need the node informer at all. The routing is always set up by cloud-controller-manager in our case. Then I raised the issue #1617 .
This PR does the following:
1. When flanneld started, check if the `alloc` is used, if used, set a `disableNodeInformer` flag
2. if `disableNodeInformer` is true, flanneld will not initialize the node informer
3. when backend calls `kubeSubnetManager`, if `kubeSubnetManager` is true, use a GET method to fetch fresh data from kube apiserver, instead of from local cache
I'm currently not sure if this will harm other users' cases. Please leave comments, thanks!
Disable …
=> disable node informers for alloc

Documentation/troubleshooting.md
The namespace of the flannel pod is "kube-flannel".
```release-note
None required
```
=> docs: fix troubleshooting

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/e2eTests.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/release.yml, .github/workflows/trivy.yml
This removes the CI warning about using deprecated Node.js 12 actions.
```release-note
None required
```
=> update checkout and setup-go GH actions to v3

dist/functional-test-k8s.sh, network/iptables.go, network/iptables_test.go
Added iptables rule that check marked packed by Kube-proxy to avoid double-NAT that could slow down the connection or in some kernel versions loss packets.
Issue: #1679
```release-note
None required
```
=> Fixed masquerade rule to avoid double NAT bug

pkg/ip/iface_windows_test.go
fix type mismatch in windows test TestGetInterfaceByIP
GetInterfaceIP4Addrs, used in windows test function TestGetInterfaceByIP (file iface_windows_test.go), returns a slice of IPAddresses. The test is done only for single IP address instead of the returned slice. This leads to a type-mismatch error. To fix this a loop was introduced to check all IP Addresses of the interface.
```release-note
None required
```
=> pkg/ip/iface_windows_test.go: fix TestGetInterfaceByIP

Documentation/MultiClusterCIDR/README.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, backend/ipip/ipip.go, backend/udp/udp_amd64.go, backend/vxlan/vxlan.go, backend/wireguard/device.go, backend/wireguard/wireguard.go, backend/wireguard/wireguard_network.go, dist/functional-test-k8s.sh, go.mod, main.go, network/iptables.go, network/iptables_test.go, pkg/ip/ip6net.go, pkg/ip/ipnet.go, subnet/config.go, subnet/config_test.go, subnet/etcd/local_manager.go, subnet/kube/cluster_cidr.go, subnet/kube/kube.go, subnet/subnet.go
This PR implements the MultiClusterCIDR feature as requested in https://github.com/flannel-io/flannel/issues/1564.
It was tested manually with Kubernetes 1.26-alpha.1.
At the moment, it is optional and is activated via a flag when starting flannel.
- [ X ] Tests
- [ X] Documentation
```release-note
None required
```
=> Implement MultiClusterCIDR feature in flannel

Documentation/troubleshooting.md
Fix document with wrong path
- [/] Documentation
=> fix: old document with wrong path :tea:

e2e/e2e-functions.sh, e2e/run-e2e-tests.sh
function e2e-pod-ready was not watching all the namespaces and failed very time.
```release-note
None required
```
=> fix randomness in k3s end to end tests

e2e/docker-compose.yml, e2e/run-e2e-tests.sh, pkg/iptables/iptables.go
Moved iptables rules from insert to append to be ordered after kube-proxy rules to fix https://github.com/k3s-io/k3s/issues/6691
It will invalidate #1650 in case other rules are already created on the nodes. This is the same behaviour of other CNIs the additional rules outside of kubernetes need to be configured accordingly.
```release-note
None required
```
=> Reordered iptables rules

Documentation/backends.md, pkg/backend/vxlan/device.go, pkg/backend/vxlan/vxlan.go, pkg/backend/vxlan/vxlan_network.go, pkg/backend/wireguard/wireguard.go, pkg/backend/wireguard/wireguard_network.go
Linked issue #1011 
Added `MTU` config to use inside the backend configuration for `vxlan` and `wireguard` backend.
The MTU configured is the MTU desired for the outgoing traffic the final MTU configured on the network interface will be `MTU - overhead`
```release-note
None required
```
=> Added MTU config for vxlan and wireguard

README.md
this PR removes the 404 link from the top-level README;
linked file was removed with commit https://github.com/flannel-io/flannel/commit/af16a77280a2135a4d7d9acdc6c4e8d1d305b2b6 
I did a brief check and all other links in the readme are ok
```release-note
None required
```
=> README.md: remove dead link to production-users.md

go.mod, go.sum
Updates the go-restful dependency from version 3.8.0 to 3.10.2 to address the following:
https://github.com/emicklei/go-restful/issues/497
This is detected as a vulnerability within Prisma Cloud (PRISMA-2022-0227).
```release-note
None required
```
=> Bump github.com/emicklei/go-restful/v3 to 3.10.2

Documentation/extension.md, pkg/backend/extension/extension.go
When dualStack support was added to flannel, it was forgotten to provide that support in the extension backend. This PR provides that by passing the lease.IPv6Subnet and attrs.PublicIPv6 parameters
```release-note
DualStack support in extension backend
```
=> Add IPv6 parameters in the extension backend

pkg/lease/lease.go, pkg/subnet/subnet.go
- Remove duplicate code by creating the "sameSubnet" function
- Removes deleteLease function which was not used anywhere
```release-note
Simplify leases code
```
=> Simplify leases code

Documentation/MultiClusterCIDR/README.md, Documentation/backends.md, Documentation/building.md, Documentation/kubernetes.md, Documentation/troubleshooting.md
These changes correct various spelling errors found in the `Documentation` project directory.
* In `Documentation/MultiClusterCIDR/README.md`, a misspelled word, `sigle`, has been corrected to `single`, [following Merriam-Webster's spelling of the word](https://www.merriam-webster.com/dictionary/single). 
* In `Documentation/backends.md`, a misspelled word, `seperate`, has been corrected to `separate`, [following Merriam-Webster's spelling of the word](https://www.merriam-webster.com/dictionary/separate).
* In `Documentation/building.md`, a misspelled word, `manully`, has been corrected to `manually`, [following Merriam-Webster's spelling of the word](https://www.merriam-webster.com/dictionary/manually).
* In `Documentation/kubernetes.md`, a misspelled word, `Acccess`, has been corrected …
=> Fix: Correct various spelling mistakes in the Documentation project directory.

pkg/subnet/etcd/subnet_test.go, pkg/subnet/kube/kube.go
In the implementation of Kubernetes API, `leaseWatchChan` did not close correctly after ctx cancellation:
https://github.com/flannel-io/flannel/blob/148b6d6a58deb864519bbc474f4c531a0799e910/pkg/subnet/kube/kube.go#L482-L484
Will cause the following loop to not end:
https://github.com/flannel-io/flannel/blob/148b6d6a58deb864519bbc474f4c531a0799e910/pkg/subnet/subnet.go#L148-L165
```release-note
None required
```
Signed-off-by: iiiceoo <iiiceoo@foxmail.com>
=> fix: goroutine leak during watch leases (kube)

Makefile
Remove dirty flag from the command that generates the TAG
```release-note
None required
```
=> Removed dirty flag

pkg/backend/vxlan/device.go
Fixes: https://github.com/flannel-io/flannel/issues/1795
after exit, flanneld will update vtep info:
```
$ docker logs ae5e1a274eae
E0821 11:40:16.145538       1 main.go:335] Error registering network: failed to configure interface flannel.1: flannel.1's mac address wanto be: 36:49:83:64:e0:11 but got: 7e:fa:35:d0:2a:d0
I0821 11:40:16.145771       1 main.go:523] Stopping shutdownHandler...
$ docker ps -a | grep flanneld
b89f5d8163e2   f18629ca5ecb                                         "/opt/bin/flanneld -…"   2 seconds ago    Up 1 second                             k8s_kube-flannel_kube-flannel-ds-9h5tc_kube-system_92426357-db8b-4f70-b536-f9de959d0881_7
ae5e1a274eae   f18629ca5ecb                                         "/opt/bin/flanneld -…"   23 seconds ago   Exited (1) 14 seconds ago …
```
=> ensure vxlan mac will be correct with systemd-network MACAddressPolicy=random

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/k3s-e2eTests.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, Makefile, go.mod, images/Dockerfile.amd64, images/Dockerfile.arm, images/Dockerfile.arm64, images/Dockerfile.ppc64le, images/Dockerfile.s390x
This PR:
* updates the go version from 1.9 to 1.20
* updates Alpine version from 3.17.3 to 3.18.4
```release-note
Update Alpine to 3.18.4 and go version to 1.20
```
=> Update Alpine and go version

chart/kube-flannel/templates/config.yaml
When using the helm chart with a wireguard psk, the value is not quoted inside `net-conf.json`.
This results in the SubnetManager config parse to fail.
```
kubectl create ns kube-flannel
kubectl label --overwrite ns kube-flannel pod-security.kubernetes.io/enforce=privileged
helm repo add flannel https://flannel-io.github.io/flannel/
helm repo update
helm install flannel --set podCidr="10.244.0.0/16" --set flannel.backend="wireguard" --set flannel.psk="SQrrIYA1R4A/zlTkJXP3WWE3Sk+20YJ7w946IGQto/o=" --namespace kube-flannel flannel/flannel
```
`kubectl -n kube-flannel logs pods/kube-flannel-ds-l28qk`
```
[..]
Failed to create SubnetManager: error parsing subnet config: invalid character 'S' after object key:value pair
```
The resulting config is
```
[..]
net-conf.json: |
{
"Network": …
```
=> Helm chart: Quote wireguard psk to fix config errors

Makefile, images/Dockerfile.riscv64
it is used to build flanneld and docker image in riscv64.
None required
=> add riscv64 support

pkg/backend/vxlan/vxlan.go, pkg/backend/vxlan/vxlan_network.go
according to https://datatracker.ietf.org/doc/html/rfc7348, vxlan cni is 24-bit. we should not use uint16 to hold it.
=> vxlan vni should not be type uint16

chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/tests/daemonset_test.yaml, chart/kube-flannel/values.yaml
when users overwrite image repository, image pull secrets may be required to have access
=> chart: add possibility for defining image pull secrets in daemonset

pkg/backend/vxlan/device.go, pkg/backend/vxlan/vxlan.go, pkg/subnet/etcd/local_manager.go, pkg/subnet/kube/kube.go, pkg/subnet/subnet.go
fixes #1828 
New feature: flag `persistent-mac` that reads the nodes annotation during startup and spins up the flannel.1 interface with the same MAC address. This can be useful when a reboot of the node happened but the old setup needs to be restored.
```release-note
The MAC address of the flannel interface is now persistent beyond restarts
```
=> feat: added persistent-mac option

pkg/backend/vxlan/device_windows.go
When the HNS network gets created, it takes a few seconds for the interface to be ready again. Sometimes, it takes more than 5  seconds for the interface to be ready and thus, the function can't find the interface and fails, hence flanneld fails.
This PR increases the time out to 20s instead of 5s to avoid that problem
```release-note
None required
```
=> Increase the time out for interface checking in windows

main.go, pkg/subnet/config.go, pkg/trafficmngr/iptables/iptables.go, pkg/trafficmngr/iptables/iptables_test.go, pkg/trafficmngr/iptables/iptables_windows.go, pkg/trafficmngr/trafficmngr.go
There are now only two methods:
- SetupAndEnsureForwardRules
- SetupAndEnsureMasqRules
This will help hide the implementation details that are specific to
iptables and nftables.
```release-note
None required
```
=> Simplify trafficmanager interface

pkg/backend/vxlan/vxlan.go, pkg/subnet/etcd/local_manager.go, pkg/subnet/kube/kube.go, pkg/subnet/subnet.go
For some unknown reason, subnetManager was using a different context than the main one, thus the `cancel()` method to clean up flannel resources will never work in this case.
This PR fixes that and subnetManager will use the main context
```release-note
None required
```
=> SubnetManager should use the main context

images/Dockerfile
The sanity check in `iptables-wrapper-installer.sh` is important in case a version of the base image for some arch doesn't include all the needed iptables-related files.
But it fails for multi-arch build so we have to use a manual test.
```release-note
None required
```
=> Use manual test to ensure iptables-* binaries are present

images/Dockerfile
The net-tools package is pretty old and iproute2 should be enough. The net-tools package provides;
```
arp, hostname, ifconfig, ipmaddr, iptunnel, mii-tool, nameif, netstat, plipconfig, rarp, route und slattach
```
and we are not using them. The only one we use is `arp` in dist/extension-vxlan but we are consuming vxlan via its own backend. This is probably why this package was used
```release-note
Removed net-tools package from the image 
```
=> Remove net-tools package from the image

pkg/subnet/kube/kube.go
Added additional chek to verify that `n.spec.podCIDRs` is rightly configured on the node
```release-note
None required
```
=> Added additional check for n.spec.podCIDRs

Documentation/adrs/add-nftables-implementation.md
```release-note
None required
```
=> add nftables adr

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> prepare for release v0.24.3

chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/values.yaml
Flannel might deploy in clusters whose nodes contain taints and thus we need the tolerations field to be configurable
```release-note
None required
```
=> Add tolerations to the helm chart

pkg/trafficmngr/iptables/iptables.go
Linked issue: https://github.com/flannel-io/flannel/issues/1906
```release-note
None required
```
=> fix: ipv6 iptables rules were created even when IPv6 was disabled

pkg/backend/vxlan/vxlan.go
fix typo in comment
```release-note
None required
```
=> chore: fix typo in comment

Makefile, pkg/backend/vxlan/device_windows.go, pkg/backend/vxlan/vxlan_windows.go, pkg/lease/lease.go
In certain windows environments, the host network is not ready by the time we acquire the lease, which makes flannel crash. This PR makes an additional check before acquiring the lease, so that we are sure the network is ready by the time we try acquiring the lease.
Apart from that, the PR:
* adds a bit more context to the errors in windows
* updates test golang version to 1.21 (in sync with go.mod)
* Fixed gofmt problems in lease.go
```release-note
Check network is ready before acquiring lease in windows
```
=> Add extra check before acquiring lease

pkg/backend/vxlan/vxlan.go, pkg/subnet/etcd/local_manager.go, pkg/subnet/kube/kube.go, pkg/subnet/subnet.go
Adds the persistency of the MAC to the v6 flannel interface too
```release-note
Flannel-v6 interface gets a persistent MAC
```
=> Add persistent-mac option to v6

Documentation/kubernetes.md, main.go, pkg/subnet/etcd/local_manager.go, pkg/subnet/kube/kube.go, pkg/subnet/subnet.go
Related to #1813 with this PR when Flannel starts it checks the node annotation and if `public-ip` or `public-ipv6`  are defined it'll use the one defined to select the network interface.
```release-note
None required
```
=> Added configuration for pulic-ip through node annotation

Documentation/extension.md, dist/extension-vxlan
Commit 645c8a126bf (Remove net-tools since it's an old package that we are not using) was incomplete.  The vxlan examples still use the arp command.  This commit updates those to use `ip neigh replace' instead.
```release-note
None required
```
=> extension/vxlan: remove arp commands from vxlan examples

main.go
This PR fixes an issue with IPv6 in case of missing configuration the empty network was wrongly initialized to 0 with an error when the bigInt comparison was used. #1968
```release-note
None required
```
=> Fixed IPv6 0 initialization

pkg/backend/wireguard/device.go
While processing node add events, flannel-wg routes are added irrespective of whether they already exist. This causes an error message for each wg peer. This might be misleading since there is actually no problem. By add or replacing the route, this can be avoided.
Fixes #1963
- [?] Tests
- [n/a] Documentation
```release-note
Avoid error message if wireguard route already exists on node.
```
=> wireguard backend: avoid error message if route already exists

pkg/backend/hostgw/hostgw_windows.go, pkg/backend/vxlan/device_windows.go, pkg/backend/vxlan/vxlan_windows.go, pkg/subnet/kube/kube.go
When the code tries to get a lease, it contacts kube-api. If dor some reason, the connectivity failed, flanneld will error out and the registration of the network will fail. This PR makes it try several times before really failing so that we can be more resilient.
This PR also replaces some wait.Poll() calls. That one is deprecated
```release-note
Retry contacting kube-api when acquiring a lease if it fails
```
=> Try several times to contact kube-api before failing

Documentation/kubernetes.md, pkg/subnet/kube/annotations.go, pkg/subnet/kube/kube.go
This change the behave added in #1948 to fix #1978
It adds two new annotation `node-public-ip` and `node-public-ipv6` to use instead.
```release-note
None required
```
=> Added node-public-ip annotation

pkg/backend/vxlan/device_windows.go
This PR fixes a bug. The wait.PollUntilContextTimeout should return true when the condition is met. It was returning false.
Apart from that, it increases the timeout to 45s. as 25s. is too tight. And also reduces the log verbosity for the logs where it finds the interface so that we can see it in all runs
```release-note
Fixes bug in vxlan windows when checking if the interface is back
```
=> Fix bug in the logic polling the interface

pkg/backend/hostgw/hostgw_windows.go
Fix bug in wait logic of hostgw-windows. The wait should stop if the bridge endpoint is already attached
```release-note
None required
```
=> Fix bug in hostgw-windows

Documentation/integrations.md, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/netpol.md, chart/kube-flannel/templates/config.yaml, chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/templates/rbac.yaml, chart/kube-flannel/values.yaml
This PR removes the clustercidr reference from the chart and the manifest and adds an initial support for the networkpolicy controller with the deployment of the container alongside the flannel daemonset #2004
```release-note
None required
```
=> Updated Flannel chart with Netpol containter and removed clustercidr

.github/workflows/e2eTests.yaml, .github/workflows/k3s-e2eTests.yml, Makefile, dist/functional-test-k8s.sh, e2e/Dockerfile, e2e/download-kubectl.sh
Update the version of k8s that we use for the end to end tests.
also change the download url for `kubectl` as the old one does not have the most recent versions
and add 90m timeouts to test workflows so that we don't consume the CI budget for no reason when there is an issue
```release-note
None required
```
=> Update k8s version in e2e tests to v1.29.8

.github/workflows/trivy.yml, pkg/backend/vxlan/vxlan.go, pkg/backend/wireguard/wireguard.go
If we try for example to use IPv6 without having configured an IPv6 ClusterCIDR, flannel can crash.
This PR makes sure flannel stops at startup with a more explicit error message.
```release-note
None required
```
=> check that the lease includes an IP address of the requested family before configuring the flannel interface

README.md, main.go
This PR adds a check to verify if the file bridge-nf-call-iptables is present to check if the br_netfilter module is loaded.
The check was done by kubeadm before but was removed from 1.30 #2068
```release-note
None required
```
=> Added checks for br_netfilter module

pkg/backend/wireguard/device.go
Although K8s, Flannel, and Wireguard, all support having k8s nodes running in a private network behind a NAT-applying firewall, the implementation of the Wireguard backend in Flannel is explicitly breaking this setup by over-zealously cleaning remote nodes. The resulting system behavior is: when a new node is started, the old node in the same private network gets its routing broken, without warning and user feedback, leading to unwanted, unexpected network timeouts. This PR removes calling that cleanup code in the Wireguard backend. 
I consider this change a bug fix, but maybe it should be treated as a new feature given the potential impact. Please advise me on what level of configurability should be added around this new behavior. 
We (@ Asimovo B.V.,  www.asimovo.com) have a production …
=> Bugfix/feature: Allow multiple nodes behind a single public IP address, e.g. remote nodes behind NAT.

README.md
Updated CNI plugins version on the README.
```release-note
None required
```
=> Updated CNI plugins version on the README

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, chart/kube-flannel/values.yaml, e2e/Dockerfile
Updated CNI image reference on the manifest to 1.6.0
```release-note
None required
```
=> Updated flannel cni image to 1.6.0

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Fixes #2158
Prepare for flannel release v0.26.3.
This step seems to have been missed when cutting the v0.26.3 branch.
```release-note
Prepare for flannel release v0.26.3.
```
=> Prepare for flannel release v0.26.3

chart/kube-flannel/templates/daemonset.yaml
Fix: Add missing MY_NODE_NAME environment variable in chart.
"NodeName" is now set to "$(my_node_name)".
```bash
I0101 11:55:44.275697       1 main.go:59] flags: []
I0101 11:55:44.301143       1 controller.go:83] Creating event broadcaster
I0101 11:55:44.301355       1 controller.go:89] Creating controller: networkpolicy.Config{FailOpen:false, AdminNetworkPolicy:false, BaselineAdminNetworkPolicy:false, QueueID:100, NodeName:"$(my_node_name)"}
```
```release-note
None required
```
=> fix: add missing MY_NODE_NAME environment variable in chart

chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/tests/daemonset_test.yaml, chart/kube-flannel/values.yaml
This feature enables more controlled installation of CNI configs in setups where more than one CNI is used. It helps prevent race conditions during initial node bootstrapping.
```release-note
Add bool to control CNI config installation using Helm
```
=> feat: add bool to control CNI config installation using Helm

chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/values.yaml
enable setting the location of the CNI directories in the helm chart.
```release-note
None required
```
=> enable setting CNI directory paths in helm chart

.github/workflows/release.yml, Makefile
As we've seen with `tj-actions/changed-files`, GHA can be compromised so we can enhance the repo's security by reducing our use of unnecessary third-party actions.
This PR removes the two third-party action that we used in our release workflow:
- softprops/action-gh-release
- yogeshlonkar/wait-for-jobs
Ref: https://www.stepsecurity.io/blog/harden-runner-detection-tj-actions-changed-files-action-is-compromised
```release-note
None required
```
=> refactor release.yaml to reduce use of potentially vulnerable GH Actions

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/e2eTests.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/k3s-e2eTests.yml, .github/workflows/release.yml, .github/workflows/trivy.yml
Pinning the GitHub Actions to specific commits instead of tags will help avoid attacks like the one affecting `tj-actions/changed-files` where the tags were retroactively changed to point to a corrupt version of the Github Action.
```release-note
None required
```
=> Pin all GHA to a specific SHA commit

pkg/backend/wireguard/wireguard.go, pkg/backend/wireguard/wireguard_network.go
Before this change, the wireguard code constructed a peer endpoint via "PeerIP + n.dev.listenPort", i.e. we used the peer's IP, but our port.
This works fine if every k8s node has the same ListenPort, which is admittedly the common setup...
However, some people may desire to use different ports for some cases, and in that case, we should respect that different port.
I've manually tested that this works in my cluster, where 1 node has different ports for wireguard from all the others.
After deploying this diff to each node, I get a working pod network.
Note: I believe this is a bugfix which shouldn't break any properly configured setups, so I didn't add an opt-in or opt-out to it. I'm happy to add an opt-in flag if we can think of any reasonable setup this would break.
```release-note
None …
```
=> Use peer's wireguard port, not our own

chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/values.yaml
- Add resources for the `kube-flannel` container to the helm chart
- Tested with helm v3.18.1 and kubernetes v1.32.5
```release-note
None required
```
=> enable setting resources in helm chart

Documentation/configuration.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, chart/kube-flannel/templates/daemonset.yaml, go.mod, main.go, pkg/subnet/kube/kube.go
Issue: #2252 
Channel event queue is a sized buffer (default=5000) and ends up blocking if there are events that are higher than the buffer size. This can happen on a large cluster with 5K nodes. Flannel sets up the informers during startup and while the informer callbacks occur asynchronously, NewSubnetManager uses a wait.PollUntilContextTimeout() to check for informer sync completion (with a timeout of 10 min). The problem is AddEvent blocks when the channel buffer is full holding the DeltaFIFO lock that is also needed by cache controller's HasSynced() which is checked in the callback for wait.PollUntilContextTimeout(). This results in a deadlock where the main thread is indefinitely blocked.
Below is the summary from stacktrace on a stuck flanneld due to this issue.
| Goroutine | …
=> Fix deadlock in startup for large clusters

go.mod, images/Dockerfile, main.go, pkg/ip/iface.go, pkg/ip/iface_windows.go
This PR adds a flag `--ip-blackhole-route` to enable a blackhole route for the local CIDR in case the bridge CNI plugin is not enabled like in Canal
This should fixes #2245
```release-note
None required
```
=> Added flag to enable blackhole route locally for Canal

chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/tests/daemonset_test.yaml, chart/kube-flannel/values.yaml
Add the ability to specify a nodeSelector in the helm chart. This is useful for situations where you might be doing multicloud and want to have split CNI. For example, a user can then tell the daemonset to only run on non-aws nodes (eg: eks.amazonaws.com/compute-type: hybrid)
```release-note
Added the option for nodeSelector to the helm chart 
```
=> Allow me to designate a nodeSelector in the helm chart
