dist/mk-docker-opts.sh, main.go
Output FLANNEL_IPMASQ to subnet.env with value of --ip-masq.
dist/mk-docker-opts converts subnet.env into Docker daemon
options.
=> Add mk-docker-opts script to write Dockerd opts

main.go
Before this patch the subnet file could become visible in a partially written state. Instead of writing to the destination, we write to a temporary file in the same directory and then `rename(2)` the file into place so that it will become visible in a consistent state.
=> Use rename(2) so that subnet file becomes atomically visible

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes/doc.go, Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes/errors.go, Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes/errors_test.go, Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes/member.go, Godeps/_workspace/src/github.com/coreos/etcd/etcdserver/etcdhttp/httptypes/member_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/id.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/id_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/set.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/set_test.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/slice.go, Godeps/_workspace/src/github.com/coreos/etcd/pkg/types/urls.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client_test.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/cluster.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/error.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/options.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests_test.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_curl_chan_test.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_update_create.go, subnet/registry.go
Sorry, I accidentally deleted my last branch https://github.com/coreos/flannel/pull/144, have to create a new PR instead :(
=> Update go-etcd to v0.4.6 with PR #195 to fix the connection leak

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/client_test.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/cluster.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/get.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/member.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/member_test.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/options.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/requests.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/set_curl_chan_test.go, Godeps/_workspace/src/github.com/coreos/go-etcd/etcd/version.go, main.go
go-etcd master is now backwards compatible with etcd v0.4.x.
=> move to go-etcd master

subnet/etcd.go, subnet/watch.go
This also fixes the cursor not being used in some cases.
=> fix handling of failed watches that result in snapshot

remote/client.go, remote/server.go, subnet/etcd.go
Watch cursor can be either impl specific type
or a string. subnet.Manager impl is responsible
for serializing/desearializing to/from string.
Fixes #185
=> Make sure the cursor is a string in JSON

remote/remote_test.go
This fixes a race that existed where the server
could get launched after the client attempted to
connect, causing the test to fail. Also changes
t.Errorf to t.Fatalf where appropriate.
Fixes #206
=> Make TestRemote retry connect on ECONNREFUSED

README.md
- Reformat to use one sentence per line.
- Update the text to reflect today's code base
- No documentation of client/server and multi network options yet.
That will be added once the code settles a bit.
=> Update docs to reflect current code base.

README.md, backend/gce/gce.go
Also updates the naming to routes to not include the network name.
=> Updates docs to include resource limits

README.md
- Added client/server section
- Added multi-network section
- Added environment variables section
=> Update readme with client/server and multi-network modes

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/files.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/files_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/listeners.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/listeners_test.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/packetconns.go, Godeps/_workspace/src/github.com/coreos/go-systemd/activation/packetconns_test.go, README.md, remote/server.go
=> Add socket activation support for server

README.md, backend/awsvpc/awsvpc.go
Permissions required ec2:ModifyInstanceAttribute. Returns a warning if
it fails. Updates readme to reflect change.
Fixes #230
=> Disable srcDest check

backend/awsvpc/awsvpc.go
If a matching route entry is present in the route table, flannel will reuse it instead of deleting it and inserting a new one. In addition, the checking for matching routes and creating routes is moved into a separate functions.
Fixes #226
=> Reuses route entry if match found

README.md
=> Updated build dependencies

backend/awsvpc/awsvpc.go
Check if the subnet is explicitly linked to a route table, if not, then
configure aws-vpc backend to use the main route table for the vpc.
Fixes #256
=> Fix seg fault when aws subnet linked to main route table

README.md, backend/alloc/alloc.go, backend/awsvpc/awsvpc.go, backend/common.go, backend/gce/gce.go, backend/hostgw/hostgw.go, backend/udp/udp.go, backend/vxlan/vxlan.go, main.go, network/network.go, subnet/etcd.go, subnet/subnet_test.go
closes #258
@eyakubovich as we need this ASAP, I’ve forked and started implementing. Since this is my first time coding on `golang`, could you please review code even if you don’t plan to merge this?
Thanks :)
=> Add PublicIP address as an option

backend/awsvpc/awsvpc.go
=> change log.Info to log.Infof

dist/mk-docker-opts.sh
- Process -m flag
- If requested, output DOCKER_OPT_IPMASQ var regardless if it's true or
false
Fixes #268
=> Actually process -m flag in mk-docker-opts.sh

backend/awsvpc/awsvpc.go
=> aws-vpc: fix typo in error message

main.go, network/network.go
CNI plugin needs to know the whole flannel network
in order to set up a route for it.
=> Add FLANNEL_NETWORK to subnet.env

Godeps/Godeps.json, Godeps/_workspace/src/github.com/coreos/pkg/flagutil/env.go, Godeps/_workspace/src/github.com/coreos/pkg/flagutil/env_test.go, Godeps/_workspace/src/github.com/coreos/pkg/flagutil/types.go, Godeps/_workspace/src/github.com/coreos/pkg/flagutil/types_test.go, main.go
=> Remove code dup and use coreos/pkg/flagutil

backend/hostgw/hostgw.go, backend/udp/udp.go, backend/vxlan/vxlan.go, remote/client.go, remote/remote_test.go, remote/server.go, subnet/etcd.go, subnet/mock_registry.go, subnet/mock_subnet.go, subnet/registry.go, subnet/subnet.go, subnet/subnet_test.go, subnet/watch.go
This PR depends on https://github.com/coreos/flannel/pull/282 (which is the first commit here too) so that one should get sorted out first.
=> subnet: add infrastructure and tests for network watches

network/manager.go, subnet/etcd.go
Caused by my misunderstanding of scope and go funcs.
Fixes: 6b68c43610071f7cb568f601fd4c4ddbe8d710ef
=> Fix running multiple networks

remote/client.go
From eyeballing #337 this might be the culprit.
/cc @eyakubovich @ssergiienko
=> remote: close response body during watch()

subnet/subnet_test.go
When using hard coded subnet values in tests,
it's important that they don't accidently end
up being the same as acquired leases.
Use SubnetMin/SubnetMax in config to segrate
hard coded and dynamically allocatable ranges.
Fixes #381
=> tests: fix bug due to random numbers being used

remote/remote_test.go, subnet/mock_etcd.go, subnet/mock_etcd_test.go, subnet/mock_registry.go, subnet/subnet_test.go, subnet/watch.go
Couple of race related bugs found by straneous
unit testing. Most of the problems are in
mocks/tests themselves.
=> Fixes a number of races

glide.lock, glide.yaml, vendor/github.com/coreos/pkg/.travis.yml, vendor/github.com/coreos/pkg/README.md, vendor/github.com/coreos/pkg/capnslog/README.md, vendor/github.com/coreos/pkg/capnslog/formatters.go, vendor/github.com/coreos/pkg/capnslog/init.go, vendor/github.com/coreos/pkg/capnslog/init_windows.go, vendor/github.com/coreos/pkg/capnslog/journald_formatter.go, vendor/github.com/coreos/pkg/capnslog/pkg_logger.go, vendor/github.com/coreos/pkg/dlopen/dlopen.go, vendor/github.com/coreos/pkg/dlopen/dlopen_example.go, vendor/github.com/coreos/pkg/dlopen/dlopen_test.go, vendor/github.com/coreos/pkg/flagutil/env_file.go, vendor/github.com/coreos/pkg/flagutil/file_env_test.go, vendor/github.com/coreos/pkg/progressutil/iocopy.go, vendor/github.com/coreos/pkg/progressutil/progressbar.go, vendor/github.com/coreos/pkg/test
This PR contains only a bump to the v2 tagged release of github.com/coreos/pkg.
This is needed in for flannel to build on Windows. ref:  https://github.com/coreos/pkg/issues/36
Once this is merged, we can continue working on the windows support for flannel.
=> Bump to pkg v2

backend/hostgw/network.go
Closes #436.
/cc @tomdee @fnordahl
=> hostgw: check for route existence before adding

backend/awsvpc/awsvpc.go
Fixes #509
It removes the invalid routes from the routetable that belong to `flannel` network.
I don't think we need to cleanup this regularly (not without client-server architecture at least) since the it is created only on instance startup.
=> aws-vpc: remove "blackholes"

network/manager.go
Improve startup logging around determining external address and
interface to use
=> network manager: Improve logging

Makefile
I found this bug with the Makefile's use of docker.
Fixes #578
=> Replacing the user id with group id.

Makefile
The build process should be non-interactive.
Fixes #580 
@tomdee can you take a look at this Makefile related PR as well?
=> Removing the -it flag from the docker build commands.

Documentation/integrations.md, Documentation/production-users.md, README.md
Production-users and Integrations pages, per the request from @philips
=> added production users and integrations pages

backend/hostgw/network.go
Only record routes in memory if not already there
Fixes #624
=> backend/hostgw: Fix memory leak

MAINTAINERS
Stefan is OOO while he finishes his degree program. Remove him for now.
:)
=> MAINTAINERS: remove steevej

Makefile
=> Build tar.gz for ppc64le, arm and arm64 arch

Documentation/kube-flannel.yml
=> kube-flannel: Add namespace for compatibility with RBAC rules

subnet/etcdv2/registry.go
=> subnet/etcdv2: Fix panic from bad error contruction

Makefile
=> update the LIB_DIR for s390x

Documentation/kube-flannel.yml
0.7.1 has some compatibility fixes for kubernetes 1.6.1
=> Update kube-flannel.yml to use 0.7.1 flannel image

pkg/ip/ipnet.go
=> network order functionality changed based on endianess

Documentation/configuration.md
addresses https://github.com/coreos/flannel/issues/463
=> docs: adding MTU note.

Documentation/running.md
addresses part of https://github.com/coreos/flannel/issues/673
=> docs: adding pointer to reservations.md.

README.md
addresses https://github.com/coreos/flannel/issues/651
=> docs: adding CNI plugin note.

main.go
Only display the logging options that actually work
=> main.go: Fix logging options

Documentation/configuration.md, main.go, subnet/etcdv2/local_manager.go, subnet/kube/kube.go, subnet/subnet.go
Allows for even more flexibility when selecting the network interface
that flannel should be using
Addresses #620
Ran multiple interface options against flannel and verified that the correct interfaces were used
=> Added ability to specify multiple ifaces and iface regexes

Documentation/Kubernetes.md, Documentation/building.md, Documentation/running.md, Documentation/troubleshooting.md, README.md
Fixes #758 
Fixes #742 
Fixes #711
=> Overhaul docs - troubleshooting, kubernetes info

backend/hostgw/hostgw.go, backend/hostgw/hostgw_network.go
Ensure that the "desired" list of routes is kept up to date even if
there are errors
Add a few logging and comments
=> backend/hostgw: Improve robustness, add logging and comments

README.md
This PR fixes the introductory sentence of Flannel. It's a dead simple one, but my eyes were bleeding and here I am.
=> Fix horrendous README typo

Documentation/Kubernetes.md, Documentation/k8s-manifests/kube-flannel-legacy.yml, Documentation/k8s-manifests/kube-flannel-rbac.yml, Documentation/kube-flannel-aliyun.yml, Documentation/kube-flannel.yml, Documentation/troubleshooting.md, README.md
=> kube-flannel.yaml: Update manifests to latest release

dist/functional-test.sh
This will make sure to delete leftover containers for every testcase.
=> Remove leftover containers

Documentation/k8s-manifests/kube-flannel-legacy.yml, Documentation/kube-flannel.yml
```release-note
None required
```
=> kube: Update manifests to v0.9.1

subnet/config.go
SubnetMin and SubnetMax must be aligned to a Subnet boundary
Fixes #430
=> subnet/config.go: Ensure that Subnets are aligned

Makefile, backend/hostgw/hostgw.go, backend/hostgw/hostgw_windows.go, backend/ipip/ipip.go, backend/route_network.go, backend/udp/udp_network_amd64.go, backend/vxlan/device.go, pkg/ip/iface.go, pkg/ip/iface_test.go, pkg/ns/ns.go
Changes to build & release Windows binaries from Linux box
```release-note
None required
```
=> Fix to build/release windows binaries from Linux

Documentation/kubernetes.md
```release-note
None required
```
=> Correct Spelling ClusterRoleBinding

.gitignore, pkg/ip/iface_windows.go
As per #832, gets flannel to run on windows (Vxlan and host-gateway to come in separate PRs after this)
=> flannel: Get flannel running on windows

Documentation/k8s-manifests/kube-flannel-legacy.yml, Documentation/kube-flannel.yml
This will only be merged when v0.10.0 is released
=> Update manifests to v0.10.0

Documentation/backends.md
=> Fix a typo

Makefile
=> Use latest Go version

Documentation/running.md
=> Update version used in doc

Documentation/kube-flannel.yml
Fix for k8s 1.12+ https://github.com/coreos/flannel/issues/1044#issuecomment-425519107
=> Do not define keys for tolerations

backend/vxlan/vxlan.go
=> Initial capitalization

Makefile
Get necessary qemu binary from
https://github.com/multiarch/qemu-user-static/releases for building.
```release-note
None required
```
=> Support build on my mbp without need install qemu-*-static

OWNERS
Creating an owners file that the ci-bots can work with
New reviewers and approvers have been added.
No release notes required
=> New maintainers and reviewers

Documentation/running.md
Fix subnet.env saved path: /var/run/flannel -> /run/flannel
=> Fix subnet.env saved path

Documentation/troubleshooting.md
```release-note
None required
```
=> Fix typo in troubleshooting document

glide.yaml
Refer https://github.com/Masterminds/glide/issues/1051
```release-note
None required
```
=> Fix typo in glide.yaml

backend/vxlan/vxlan_windows.go
Fixes #1111 
Instead of querying an existing Overlay network for a DR MAC address, we proceed with creating the Flannel network. We then get the DR MAC from this network and update the lease accordingly.
The first SubnetAdded event will be ignored by other Linux and Windows nodes since the VtepMAC will be nil. The second SubnetAdded event will contain the MAC so event handling will continue as expected.
```release-note
Remove dependency on pre-existing Overlay network for Flannel VXLAN for Windows.
```
=> Remove dependency on pre-existing Overlay network for Flannel VXLAN for Windows.

subnet/kube/kube.go
Like calico : https://github.com/projectcalico/node/pull/134
http://www.deadunicornz.org/blog/2017/11/08/gce-and-self-hosted-k8s-1-dot-6-noroutecreated/index.html
There is an annoying bug since Kubernetes 1.6 running on GCE with Calico/Flannel networking operating via CNI plugin interface. You may experience same issue if kubelet on your nodes runs with options `--network-plugin=cni --cloud-provider=gce`
When a new node is added to the k8s cluster it’s recognized as ‘Ready’ but no pods except Calico/Flannel pod are being scheduled there.
Please include 
- bug fix
- Fix the `NetworkUnavailable` `False` on GCE with flannel and vxlan backend
- manual test : deploy on our infra. 
- kubeSubnetManager components are affected by this PR
Ref code : …
=> Needs to clear NodeNetworkUnavailable flag on Kubernetes

Documentation/kube-flannel.yml
Two PRs adding cniVersion to the configmap was merged, resulting in two lines.
```release-note
None required
```
=> Remove duplicate cniVersion in configmap

Documentation/kube-flannel.yml
Just a small typo fix and yaml indent which should have no influence to the deployment at all.
```release-note
None required
```
=> Fix typo and invalid indent in kube-flannel.yml

main.go
=> Use publicIP lookup iface if --public-ip indicated

subnet/watch.go
=> fix deleteLease

Makefile
Using GO_VERSION defined in Makefile for all the golang docker image.
```release-note
None required
```
=> Fixing golang docker image tag in makefile

Documentation/backends.md
Completion / supplement of the documentation for the IPsec backend.
In readme: added a hint for firewall rules in backend documentation (IPsec backend).
Could help users to use this backend without problems.
=> Added a hint for firewall rules

README.md
Signed-off-by: Chris Kim <oats87g@gmail.com>
This enhances the `README.md` to add the community meeting information.
```release-note
None required
```
=> Add community meeting section to README

OWNERS
Adding reviewers to the project.
```release-note
None required
```
=> New reviewers to OWNERS file

Documentation/kube-flannel.yml
For testing release v0.13.0-rc2
N/A
```release-note
None required
```
=> multi arch for release 13-rc2

Documentation/kube-flannel.yml
For release v0.13.0
```release-note
None required
```
@AleksandrNull Review please.
=> daemonset upgrade from v0.13.0-rc2 to v0.13.0

.travis.yml, Makefile, go.mod
upgrades to go1.15.5, should solve https://github.com/coreos/flannel/issues/1365
=> upgrade to go1.15.5

Documentation/alicloud-vpc-backend-cn.md, Documentation/alicloud-vpc-backend.md
* preserve AccessKey & AccessKeySecret environment on `sudo`
* fix some typo in doc.
Just document improvement not need release note.
```release-note
None
```
=> preserve AccessKey & AccessKeySecret environment on `sudo`

Documentation/kube-flannel.yml
For the candidate release 13.1-rc1
=> move tag to 13.1-rc1

backend/hostgw/hostgw_windows.go
Skip the error if the gateway endpoint is existed, #1391
=> fix(host-gw): failed to restart if gateway hnsep existed

Documentation/upgrade.md
This commit introduces documentation about flannel upgrade/downgrade procedure.
=> Documentation for the Flannel upgrade/downgrade procedure

Documentation/backends.md, Documentation/tencentcloud-vpc-backend.md, backend/alivpc/alivpc.go, backend/tencentvpc/tencentvpc.go, backend/tencentvpc/tencentvpc_windows.go, go.mod, go.sum, main.go, network/iptables.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/LICENSE, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/credentials.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/errors/errors.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/request.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/http/response.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/client_profile.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/profile/http_profile.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/sign.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/common/types.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/client.go, vendor/github.com/tencentcloud/tencentcloud-sdk-go/tencentcloud/vpc/v20170312/models.go, vendor/modules.txt
New feature:
Add tencent cloud VPC network support
```release-note
None required
```
=> Add tencent cloud VPC network support

Documentation/kube-flannel.yml
Change to reflect the new release v0.14.0
=> release v0.14.0

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
Moving the Alpine version from 3.12 to 3.13
```release-note
Upgrade Alpine version to 3.13
```
=> Upgrade Alpine version

main.go, subnet/kube/kube.go
=> add flag setNodeNetworkUnavailable

Documentation/configuration.md, backend/hostgw/hostgw.go, backend/route_network.go, backend/route_network_test.go, subnet/kube/kube.go
Add dual stack support to host-gw backend. Currently only work with
linux now. Other limitations are the same as for the vxlan backend.
```release-note
Dual-stack support for flannel with host-gw backend
```
=> host-gw (linux): Add dual stack support

Documentation/kube-flannel.yml
This moves to the latest version of the flannel-cni which integrates with v1.0 of:
github.com/containernetworking/cni
github.com/containernetworking/plugins
=> Move to the newer flannel-cni

.github/workflows/release.yml, Dockerfile.arm64, Makefile
This PR makes it possible to push images into the dockerhub registry `flannelcni/flannel` when creating a release in the project
It also creates a flannel:latest image that we can use in the documentation
```release-note
None required
```
=> Automate the release using github actions

backend/wireguard/device.go, backend/wireguard/wireguard.go, backend/wireguard/wireguard_network.go, backend/wireguard/wireguard_windows.go
The wireguard PR was breaking the build of flanneld.exe. This PR excludes the wireguard files from being built when building flanneld.exe
```release-note
None required
```
=> Fix windows build

Documentation/kube-flannel.yml, README.md
Updates the docs to the latest release
=> Update docs to the latest flannel release v0.16.1

network/iptables.go
Add a comment to simplify debugging of iptables. This way we know that these tables were created by flannel
```release-note
Add comment to the created iptables
```
=> Add comment to the created iptable rules

subnet/kube/kube.go
Added additional log to show the Kubernetes pod network CIDR  configured.
```release-note
None required
```
=> Added additional log to show pod CIDR

Documentation/configuration.md, Documentation/kube-flannel.yml
Updated the image with the new flannel cni plugin
```release-note
Use the v1.0.1 of the flannel binary
```
=> Update kube-flannel-cni image

Documentation/kube-flannel.yml
Update the docs to point to the new release
```release-note
Release 0.16.3
```
=> Update kube-flannel manifest to 0.16.3

.github/workflows/golangci-lint.yaml, backend/awsvpc/awsvpc.go, backend/extension/extension.go, backend/extension/extension_network.go, backend/gce/api.go, backend/ipsec/handle_charon.go, backend/ipsec/ipsec_network.go, backend/route_network.go, backend/udp/cproxy_amd64.go, backend/udp/udp_network_amd64.go, backend/vxlan/vxlan_network.go, backend/wireguard/device.go, backend/wireguard/wireguard_network.go, main.go, network/iptables.go, network/iptables_test.go, pkg/ip/iface.go, pkg/ip/iface_test.go, pkg/ip/ip6net.go, pkg/mac/mac_test.go, subnet/etcdv2/local_manager.go, subnet/etcdv2/mock_etcd.go, subnet/etcdv2/mock_etcd_test.go, subnet/etcdv2/registry.go, subnet/etcdv2/registry_test.go, subnet/etcdv2/subnet_test.go, subnet/kube/kube.go, subnet/subnet_test.go
The current flannel code was full of lint errors because we were not running any lint tool. This PR adds a lint tool to github actions and fixes all lint errors
```release-note
None required
```
=> Add golangci-lint github action and fix all errors

Documentation/kube-flannel.yml
Adapts manifest to the new flannel 0.17.0 release
```release-note
None required
```
=> Change manifest to use the 0.17.0 images

Makefile, dist/functional-test-k8s.sh, dist/functional-test.sh, images/iperf3/Makefile
Adding pass of some parameters which are needed to do cross-arch builds.
=> ARM64 build fix

Documentation/configuration.md, subnet/config.go
- fix description of `SubnetLen`, `SubnetMin`, `IPv6SubnetLen`, `IPv6SubnetMin`. 
- [SubnetLen](https://github.com/flannel-io/flannel/blob/master/subnet/config.go#L77)
- [SubnetMin](https://github.com/flannel-io/flannel/blob/master/subnet/config.go#L96)
- [IPv6SubnetLen](https://github.com/flannel-io/flannel/blob/master/subnet/config.go#L134)
- [IPv6SubnetMin](https://github.com/flannel-io/flannel/blob/master/subnet/config.go#L153)
- fix typo about why we skip over the first subnet
=> fix document and comment of configuration

Documentation/kube-flannel.yml
Update flannel to the new release
```release-note
None required
```
=> Update new flannel version

go.mod, go.sum, vendor/github.com/vishvananda/netlink/filter.go, vendor/github.com/vishvananda/netlink/filter_linux.go, vendor/github.com/vishvananda/netlink/nl/nl_linux.go, vendor/github.com/vishvananda/netlink/nl/tc_linux.go, vendor/modules.txt
Updated netlink to fix Centos 7 issue.
#1574 #1576
```release-note
None required
```
=> Updated netlink library to 1.2.1

Documentation/kube-flannel.yml
```release-note
None required
```
=> Update flannel version 0.18.1

.github/workflows/e2eTests.yaml, Makefile
```release-note
None required
```
=> clarify the error logs for the CI pipeline

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml
Update kube-flannel yaml files with the newer version
=> Updated flannel version to v0.19.0

.github/workflows/release.yml, .gitignore
```release-note
None required
```
=> upload release artifacts automatically

backend/wireguard/device.go
Fixed wireguard interface MTU with the overhead as the pod interface
```release-note
None required
```
=> Fixed wireguard interface MTU with the overhead

network/iptables_restore.go
Fixed `iptables-restore` version check when the version is older than 1.6.2 where `--version` flag wasn't available.
```release-note
None required
```
=> Fixed iptables-restore version check in case of version older than 1.6.2

Documentation/building.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml
Updated Flannel release version
```release-note
None required
```
=> Updated Flannel version to 0.19.2

subnet/kube/kube.go
Added a few comments on top of some relevant functions to help understand the code better
```release-note
None required
```
=> Add some extra comments to help understand the code

.github/stale.yaml
```release-note
None required
```
=> Add stale bot to flannel repo

main.go, subnet/etcd/local_manager.go, subnet/etcd/mock_subnet.go, subnet/kube/kube.go, subnet/subnet.go
fix https://github.com/flannel-io/flannel/issues/1646
```release-note
back off set NodeNetworkUnavailableFalse after subnet.env file in kube subnet mode.
```
=> back off set NodeNetworkUnavailableFalse

Documentation/backends.md, Documentation/configuration.md
=> Fixes backend configuration documentation

Documentation/building.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml
Updates all manifests to the next new version 0.20.0
```release-note
None required
```
=> Update manifests to 0.20.0

network/iptables.go, network/iptables_test.go, network/iptables_windows.go
Added check to ensure `FLANNEL-FWD` and `FLANNEL-POSTRTG`
Fix #1668
```release-note
None required
```
=> Added check to ensure the iptables chain

Documentation/building.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml
Update flannel version to 0.20.1
```release-note
None required
```
=> Update flannel version to 0.20.1

Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x
Update alpine version to 3.16 to build the image.
```release-note
None required
```
=> Update alpine version to 3.16

Makefile, dist/functional-test-k8s.sh
Update Hyperkube K8s version for the functional tests
```release-note
None required
```
=> Update Hypekube k8s version

Documentation/building.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml
Update Flannel version to v0.20.2
```release-note
None required
```
=> Update flannel to v0.20.2

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/e2eTests.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/release.yml, .github/workflows/trivy.yml, Dockerfile.amd64, Dockerfile.arm, Dockerfile.arm64, Dockerfile.ppc64le, Dockerfile.s390x, Documentation/building.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Makefile, dist/functional-test-k8s.sh, network/iptables.go, network/iptables_test.go, pkg/ip/iface_windows_test.go, subnet/kube/kube.go
Backport of Flannel v0.20.2 for K8s 1.23
```release-note
None required
```
=> Backport of Flannel v0.20.2

network/iptables_windows.go
```release-note
None required
```
=> adapt iptables_windows.go to the new API

Documentation/k8s-old-manifests/kube-flannel-legacy.yml, Documentation/kube-flannel-old.yaml, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/minikube.yml
These limits create performance issues on large clusters and are not consistent with current best practices.
```release-note
None required
```
=> remove cpu and memory limits from manifests

Documentation/backends.md, Documentation/running.md, README.md
Update documentation to fix flannel binary link and updated backend documentation (#1704).
=> Backend docs update

.github/workflows/release.yml
Removed `docker/build-push-action` to fix wrong images pushed during the release that led to an error during manifest creation.
```release-note
None required
```
=> Removed docker push build action

images/Dockerfile.amd64, images/Dockerfile.arm, images/Dockerfile.arm64, images/Dockerfile.mips64le, images/Dockerfile.ppc64le, images/Dockerfile.s390x
```release-note
None required
```
=> always upgrade packages when creating the final image

images/Dockerfile.amd64, images/Dockerfile.arm, images/Dockerfile.arm64, images/Dockerfile.mips64le, images/Dockerfile.ppc64le, images/Dockerfile.s390x
```release-note
None required
```
=> update alpine to 3.17.2

Documentation/building.md, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml
the documentation needed to be updated to refer to the latest release, v0.21.1.
I performed a find:replace for v0.20.2->v0.21.1 across the entire codebase. (the only occurrences were in the Documentation dir)
```release-note
None required
```
=> documentation: use latest release

Documentation/kustomization/kube-flannel-psp/kustomization.yaml, Documentation/kustomization/kube-flannel/kustomization.yaml, Makefile
As suggested by @maxmoehl in #1731 removed components from the kustomization process and improved the manifest creation during release.
```release-note
None required
```
=> Removed component from kustomzation manifest process

Makefile, dist/functional-test.sh, e2e/Dockerfile, e2e/e2e-functions.sh, e2e/run-e2e-tests.sh, pkg/subnet/etcd/local_manager.go, pkg/subnet/etcd/mock_registry.go, pkg/subnet/etcd/registry.go, pkg/subnet/etcd/registry_test.go, pkg/subnet/etcd/subnet_test.go, pkg/subnet/kube/kube.go, pkg/subnet/subnet.go, pkg/subnet/watch.go
Refactor etcd client code to use channels
This allows us to use the etcd API in a more idiomatic way
and should handle better the cases where etcd sends empty events.
Issue: https://github.com/flannel-io/flannel/issues/1714
```release-note
None required
```
=> Fix etcd index outofrange

Makefile, README.md, chart/kube-flannel/Chart.yaml, chart/kube-flannel/templates/config.yaml, chart/kube-flannel/templates/daemonset.yaml, chart/kube-flannel/templates/namespace.yaml, chart/kube-flannel/templates/rbac.yaml, chart/kube-flannel/templates/serviceaccount.yaml, chart/kube-flannel/values.yaml
This PR is a WIP based on #1426 
The idea is to generate the helm chart on a tgz archive with the right version during release publishing it with the release files.
The command to install it through helm should be like this
```
helm install flannel --set podCidr="10.244.0.0/16" https://github.com/flannel-io/flannel/releases/latest/download/flannel.tgz
```
```release-note
None required
```
=> Add helm chart  to deploy flannel

Documentation/building.md, README.md
Added instruction to install CNI network plugins on README and removed reference of older building process (master is not deployed any more and the release process is automated)
```release-note
None required
```
=> Added CNI plugins reference and removed older build docs

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel-psp/kustomization.yaml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, README.md, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml, e2e/run-e2e-tests.sh
Update Flannel version reference to `v0.21.3` before release.
```release-note
None required
```
=> Update Flannel to v0.21.3

pkg/iptables/iptables.go
Fix iptables rules in case `random-fully` is not supported issue: https://github.com/k3s-io/k3s/issues/7096
```release-note
None required
```
=> Fixed iptables rules in case random-fully is not supported

Documentation/backends.md
Update documentation for VXLAN used on raspberry pi #1747 
```release-note
None required
```
=> Update backend documentation for VXLAN on raspberry pi

Documentation/configuration.md
Updated documentation considering the MTU new backend config.
=> Added MTU config reference on documentation

.github/workflows/release.yml, Makefile, README.md, chart/README.md, docs/README.md, docs/index.yaml
Update Github action when a new release is created to deploy the index.yaml file as github page to use it for the helm repository. The index.yaml file on this PR will be deployed manually after the PR is merged and it refers to the latest version released v0.21.4.
#1752
```release-note
None required
```
=> Update github action to create github pages for helm repo

README.md
A little simplification and a more traditional installation via helm.
In additional to #1754 for #1752
```release-note
None required
```
=> Update installation block in readme

images/Dockerfile.amd64, images/Dockerfile.arm, images/Dockerfile.arm64, images/Dockerfile.mips64le, images/Dockerfile.ppc64le, images/Dockerfile.s390x
Update Alpine build images
```release-note
None required
```
=> Update alpine images

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel-psp/kustomization.yaml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Update flannel version before the release
```release-note
None required
```
=> Update Flannel to v0.21.5

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel-psp/kustomization.yaml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Update flannel version before the release
```release-note
Move manifests to v0.22.0
```
=> Update flannel to v0.22.0

pkg/backend/extension/extension.go, pkg/subnet/kube/kube.go
The extension backend was missing ipv6 support. This PR adds it 
```release-note
ipv6-only for the extension backend
```
=> Add ipv6-only support for extension backend

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel-psp/kustomization.yaml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Change manifests
```release-note
Update cni plugin to v1.2.0 and flannel to v.0.22.1
```
=> Flannel new release

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> Update manifests to v0.22.2

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> prepare for v0.24.0 release

.github/workflows/release.yml
```release-note
None required
```
=> add missing riscv64 in docker manifest create step

pkg/powershell/powershell.go
This PR improves the powershell logging of flanneld.exe, as explained in https://github.com/flannel-io/flannel/issues/1851, depending on the problem, the logs are currently useless
```release-note
Improve powershell log to provide more useful output
```
=> Improve the log from powershell

pkg/backend/vxlan/device_windows.go, pkg/backend/vxlan/vxlan_windows.go, pkg/ipmatch/match.go
This PR does two things:
* Extends support of the flag `--iface` to windows.
* Exits if we are in Windows and use the flag `--iface-can-reach`
```release-note
Support --iface in Windows
```
=> Provide support to select the interface in Windows

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Update docs to use the newer version
```release-note
Update docs to use v0.24.1
```
=> Prepare for v0.24.1 release

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Version bump update
```release-note
None required
```
=> Prepare for v0.24.2 release

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/e2eTests.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/k3s-e2eTests.yml, .github/workflows/release.yml, .github/workflows/trivy.yml
since node16 is going to be deprecated soon
```release-note
None required
```
=> update many GH actions to migrate to node 20

.github/workflows/build.yaml, .github/workflows/codeql-analysis.yml, .github/workflows/e2eTests.yaml, .github/workflows/golangci-lint.yaml, .github/workflows/k3s-e2eTests.yml, .github/workflows/release.yml, .github/workflows/trivy.yml, go.mod, go.sum
Update go version
```release-note
Build with go 1.21 version 
```
=> Move to go1.21

Documentation/building.md, Makefile, dist/functional-test-k8s.sh, dist/functional-test.sh, e2e/Dockerfile
```release-note
None required
```
=> testing: update k8s, bash_unit and etcd versions

main.go
```release-note
None required
```
=> chore: fix typo

chart/kube-flannel/values.yaml
This PR restores the default chart behavior which was tolerating all kind of taints. It even expands it to "NoSchedule" too
```release-note
The flannel chart now tolerates all kind of taints
```
=> Restore default chart behaviour

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> prepare for release v0.25.0

pkg/backend/vxlan/vxlan_network.go, pkg/lease/lease.go
Updated lease.go with String function for leaseAttr and added a log on vxlan subnet handler with the attr info.
```release-note
None required
```
=> Added leaseAttr string method with logs on VxLan

pkg/trafficmngr/iptables/iptables_windows.go, pkg/trafficmngr/nftables/nftables_windows.go
```release-note
None required
```
=> remove unimplemented error in windows trafficmngr

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> Prepare for release v0.25.1

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, chart/kube-flannel/values.yaml
Updates the flannel binary to the latest version
```release-note
Bump flannel cni version to v1.4.1
```
=> Update cni plugin version to v1.4.1

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> Prepare for release v0.25.2

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Update files for flannel v0.25.3
```release-note
None required
```
=> Prepare Flannel update to v0.25.3

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, chart/kube-flannel/values.yaml
Bumps flannel-cni version
```release-note
None required
```
=> Update flannelCNI version

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
Prepare the update to v0.25.5
```release-note
None required
```
=> Prepare update to v0.25.5

chart/kube-flannel/values.yaml
Fixed Values file on the chart to disable the NFTables by default
```release-note
None required
```
=> Fixed values file on flannel chart

README.md
Updated README.md with the latest version of the CNI plugin (1.5.1) and added the architecture check.
```release-note
None required
```
=> Updated README with latest CNI plugin version

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> Bump cni-plugin to v1.5.1-flannel2

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> prepare release v0.25.6

go.mod, go.sum, pkg/backend/route_network_test.go
```release-note
None required
```
=> Update netlink to v1.3.0

pkg/ipmatch/match.go
This PR fixes #2045 setting the right IPv6 address in case of an IPv6 only configuration.
```release-note
None required
```
=> Fixed IPv6 chosen in case of public-ipv6 configured

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> prepare flannel release v0.25.7

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> prepare to release v0.26.0

main.go
Added the check if the os is not windows before checking if br_netfilter is enabled.
Fixes https://github.com/rancher/rke2/issues/7215
```release-note
None required
```
=> Added check to not check br_filter in case of windows

.github/workflows/release.yml, Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel-psp/kustomization.yaml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/values.yaml
This PR adds move the reference for the used image on the chart to the github registry and publish the image on it when a new release is created
```release-note
None required
```
=> Moved to github container registry

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, README.md, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml, e2e/Dockerfile
Update flannel version reference to `v0.26.4` before new release.
```release-note
None required
```
=> Prepare to update to v0.26.4

chart/kube-flannel/templates/config.yaml, chart/kube-flannel/values.yaml
This PR adds `cniConf` value on the chart to manually edit the cni conf file that will be used with Flannel
```release-note
None required
```
=> Added cni file configuration on the chart

.github/workflows/release.yml
This was removed accidentally when moving refactoring the chart release.
```release-note
None required
```
=> Upload chart archive with the release files

.github/workflows/release.yml
```release-note
None required
```
=> add missing GH_TOKEN env var in release.yaml

.github/dependabot.yml
Using groups will make dependabot create one PR for all k8s, etcd or tencent dependencies instead of several individual ones.
```release-note
None required
```
=> Organize dependabot PR's more clearly by using groups

.github/workflows/release.yml, Makefile
```release-note
None required
```
=> Fix release workflow

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml, go.mod
move to go 1.23.6 and prepare to update to v0.26.7
```release-note
None required
```
=> move to go 1.23.6 and prepare to update to v0.26.7

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, README.md, chart/kube-flannel/values.yaml, e2e/Dockerfile
Update to the latest flannel cni-plugins v1.7.1
```release-note
None required
```
=> Update to the latest flannel cni-plugins v1.7.1

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> Prepare for release v0.27.0

images/Dockerfile
Refactor the Dockerfile to make it a bit easier to read and speed up the build slightly
```release-note
None required
```
=> Optimize Dockerfile

Documentation/kube-flannel-psp.yml, Documentation/kube-flannel.yml, Documentation/kustomization/kube-flannel-psp/kube-flannel-psp.yml, Documentation/kustomization/kube-flannel/kube-flannel.yml, Documentation/kustomization/kube-flannel/kustomization.yaml, chart/kube-flannel/Chart.yaml, chart/kube-flannel/values.yaml
```release-note
None required
```
=> Prepare release v0.27.2

OWNERS
Removed Brandon Philips (me) from approvers list. I am no longer active in the project.
=> OWNERS: remove philips
